"use client";

import { useState } from "react";
import type { UiLanguage } from "../i18n/messages";
import { DataTable, Metric, PanelTitle } from "./shared";

export function Devices({notify,lang}:{notify:(v:string)=>void;lang:UiLanguage}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const [tab,setTab] = useState<"devices"|"points"|"history"|"connectors">("devices");
  const [historyMetric,setHistoryMetric] = useState("active_power");
  const [historyPeriod,setHistoryPeriod] = useState("24h");
  const [historySources,setHistorySources] = useState([true,true,true,false]);
  const [connectorStatus,setConnectorStatus] = useState(["active","active","configuring","available"]);
  const statusLabel=(status:string)=>status==="active"?t("Активен","Active"):status==="configuring"?t("Конфигуриране","Configuring"):status==="available"?t("Наличен","Available"):status==="installed"?t("Инсталиран","Installed"):t("Тест успешен","Test passed");
  const devices = [[t("PV инвертор 01","PV inverter 01"),"Deye SUN-50K-SG01HP3","Modbus TCP",t("Онлайн","Online"),"48.6 kW",t("8 сек.","8 sec")],[t("PV инвертор 02","PV inverter 02"),"Sungrow SG125CX-P2","Modbus TCP",t("Онлайн","Online"),"72.4 kW",t("6 сек.","6 sec")],[t("PV инвертор 03","PV inverter 03"),"Huawei SUN2000-100KTL","Modbus TCP",t("Онлайн","Online"),"68.8 kW",t("7 сек.","7 sec")],[t("PV инвертор 04","PV inverter 04"),"Growatt MAX 125KTL3-X","Modbus RTU",t("Онлайн","Online"),"58.8 kW",t("9 сек.","9 sec")],["BESS PCS","TESVOLT TPS-E","Modbus TCP",t("Онлайн","Online"),"+41.1 kW",t("7 сек.","7 sec")],["BMS Controller","Deye BOS-G","CAN / TCP",t("Онлайн","Online"),"72% SOC",t("7 сек.","7 sec")],[t("Мрежов електромер","Grid meter"),"Janitza UMG 604","Modbus TCP",t("Онлайн","Online"),"−83.2 kW",t("5 сек.","5 sec")],[t("Електромер на товар","Load meter"),"Schneider PM8000","Modbus TCP",t("Онлайн","Online"),"124.3 kW",t("5 сек.","5 sec")],[t("EV зарядна станция 01","EV charger 01"),"ABB Terra AC","OCPP 1.6",t("Онлайн","Online"),"11.0 kW",t("12 сек.","12 sec")],[t("EV зарядна станция 02","EV charger 02"),"Wallbox Commander","OCPP 1.6",t("Онлайн","Online"),"22.0 kW",t("10 сек.","10 sec")],[t("Метеостанция","Weather station"),"Kipp & Zonen","RS-485",t("Внимание","Warning"),"844 W/m²",t("2 мин.","2 min")],[t("Защитно реле","Protection relay"),"Siemens 7SJ82","IEC 61850",t("Онлайн","Online"),t("Нормално","Normal"),t("6 сек.","6 sec")]];
  const metrics = [["active_power",t("Активна мощност","Active power"),t("PV инвертор 01","PV inverter 01"),"kW",t("Изход","Output"),"48.6",t("8 сек.","8 sec")],["daily_yield",t("Енергия днес","Energy today"),t("PV инвертор 01","PV inverter 01"),"kWh",t("Изход","Output"),"286.4",t("8 сек.","8 sec")],["soc",t("Състояние на заряд","State of charge"),"BMS Controller","%",t("Двупосочна","Bidirectional"),"72.0",t("7 сек.","7 sec")],["charge_limit",t("Лимит заряд","Charge limit"),"BESS PCS","kW",t("Команда","Command"),"450",t("7 сек.","7 sec")],["grid_power",t("Поток към мрежата","Grid flow"),t("Мрежов електромер","Grid meter"),"kW",t("Двупосочна","Bidirectional"),"−83.2",t("5 сек.","5 sec")],["ev_power_limit",t("EV мощностен лимит","EV power limit"),t("EV парк","EV park"),"kW",t("Команда","Command"),"32.0",t("12 сек.","12 sec")]];
  const connectors = [["Deye Cloud + Modbus",t("Инвертори / BMS","Inverters / BMS"),"Telemetry + control"],["Sungrow iSolarCloud",t("Инвертори / BESS","Inverters / BESS"),"Telemetry + control"],["Huawei FusionSolar",t("Инвертори / BESS","Inverters / BESS"),"Telemetry"],["Growatt ShineServer",t("Инвертори / BESS","Inverters / BESS"),"Telemetry + control"]];
  const advanceConnector=(i:number)=>setConnectorStatus(s=>s.map((x,n)=>n===i?(x==="available"?"installed":x==="installed"?"configuring":x==="configuring"?"tested":"active"):x));
  const sourceNames=["PV inverter 01","PV inverter 02","BESS PCS","Grid meter"];
  const sourceColours=["solar","blue","green","purple"];
  const historyValues=[[42,38,35,32,34,41,52,68,74,70,63,58],[61,57,52,48,51,59,70,82,89,84,78,72],[26,24,22,20,18,31,47,58,52,43,38,33],[72,68,61,57,60,72,81,93,84,76,70,66]];
  const tabs:[typeof tab,string][]=[["devices",t("Устройства","Devices")],["points",t("Метрични точки","Metric points")],["history",t("Исторически данни","Historical data")],["connectors",t("Конектори","Connectors")]];
  return <>
    <div className="device-toolbar"><div className="searchbox">⌕ <input aria-label={t("Търсене на устройство","Search devices")} placeholder={t("Търсене на устройство...","Search devices...")}/></div><button className="secondary-btn" onClick={()=>notify(t("Сканирането откри 2 нови устройства","Scan found 2 new devices"))}>↻ {t("Открий устройства","Discover devices")}</button><button className="primary-btn" onClick={()=>notify(t("Каталогът е отворен","Catalog opened"))}>+ {t("Добави устройство","Add device")}</button></div>
    <div className="subnav">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==="devices"&&<><section className="kpis compact-kpis"><Metric label={t("Устройства","Devices")} value="12" unit={t("общо","total")} badge="" type="charge"/><Metric label={t("Онлайн","Online")} value="11" unit={t("активни","active")} badge="91.7%" type="spark solar-spark"/><Metric label={t("Комуникация","Communication")} value="98.6" unit="%" badge={t("стабилна","stable")} type="spark load-spark"/><Metric label={t("Последна команда","Latest command")} value="14:31" unit={t("ч.","h")} badge={t("изпълнена","executed")} type="price"/></section><article className="card table-card devices-table"><PanelTitle eyebrow="SCADA / COMMUNICATION" title={t("Всички устройства","All devices")}/><DataTable headers={[t("Устройство","Device"),t("Модел","Model"),t("Протокол","Protocol"),t("Статус","Status"),t("Последни данни","Latest data"),t("Обновено","Updated")]} rows={devices}/></article></>}
    {tab==="points"&&<article className="card table-card metric-table"><PanelTitle eyebrow={t("ЕДИНЕН МОДЕЛ НА ДАННИТЕ","UNIFIED DATA MODEL")} title={t("Метрични точки и права за команда","Metric points and command permissions")} action={<button className="primary-btn" onClick={()=>notify(t("Метричните точки са синхронизирани","Metric points synchronised"))}>{t("Синхронизирай","Synchronise")}</button>}/><DataTable headers={["ID",t("Име","Name"),t("Източник","Source"),t("Единица","Unit"),t("Посока","Direction"),t("Стойност","Value"),t("Обновено","Updated")]} rows={metrics}/><div className="mapping-note"><i>↔</i><span><strong>{t("Нормализация на данните","Data normalisation")}</strong><small>{t("Различните марки се превеждат към общи EMS точки. Командните точки се активират само след проверка на права и безопасни граници.","Different brands are mapped to common EMS points. Command points are enabled only after permission and safety-limit validation.")}</small></span></div></article>}
    {tab==="history"&&<section className="telemetry-history">
      <article className="card telemetry-controls"><PanelTitle eyebrow={t("OPENREMOTE DATAPOINTS","OPENREMOTE DATAPOINTS")} title={t("Сравнение на устройства и измервания","Compare devices and measurements")}/><label><span>{t("Метрика","Metric")}</span><select value={historyMetric} onChange={e=>setHistoryMetric(e.target.value)}><option value="active_power">{t("Активна мощност · kW","Active power · kW")}</option><option value="soc">SOC · %</option><option value="temperature">{t("Температура · °C","Temperature · °C")}</option><option value="energy">{t("Енергия · kWh","Energy · kWh")}</option></select></label><div className="history-source-list">{sourceNames.map((name,i)=><button key={name} className={historySources[i]?`active ${sourceColours[i]}`:""} onClick={()=>setHistorySources(s=>s.map((v,n)=>n===i?!v:v))}><i/>{name}<b>{historySources[i]?"✓":"+"}</b></button>)}</div><small>{t("Изберете няколко източника с еднаква единица за директно сравнение.","Select multiple sources with the same unit for direct comparison.")}</small></article>
      <article className="card telemetry-chart-card"><div className="telemetry-chart-head"><div><p>{t("АКТИВНА МОЩНОСТ ВЪВ ВРЕМЕТО","ACTIVE POWER OVER TIME")}</p><h2>{t("Solar Park East · синхронизирани серии","Solar Park East · synchronised series")}</h2></div><div>{["24h","7d","30d","custom"].map(p=><button key={p} className={historyPeriod===p?"active":""} onClick={()=>setHistoryPeriod(p)}>{p==="custom"?t("Период","Range"):p}</button>)}</div></div><div className="telemetry-chart-grid"><span>125</span><span>100</span><span>75</span><span>50</span><span>25</span><span>0 kW</span><div className="telemetry-bars">{historyValues[0].map((_,hour)=><div className="telemetry-hour" key={hour}>{historyValues.map((series,source)=>historySources[source]&&<i key={source} className={sourceColours[source]} style={{height:`${series[hour]}%`}} title={`${sourceNames[source]} · ${series[hour]} kW`}/>)}<em>{hour%2===0?`${String(hour*2).padStart(2,"0")}:00`:""}</em></div>)}</div></div><div className="telemetry-legend">{sourceNames.map((name,i)=>historySources[i]&&<span key={name}><i className={sourceColours[i]}/>{name}<b>{historyValues[i].at(-1)} kW</b></span>)}</div><div className="data-quality-strip"><span><i>✓</i><b>{t("Пълнота на данните","Data completeness")}</b><strong>99.4%</strong></span><span><i>↻</i><b>{t("Последно обновяване","Last update")}</b><strong>{t("преди 6 сек.","6 sec ago")}</strong></span><span><i>◎</i><b>{t("Резолюция","Resolution")}</b><strong>15 min</strong></span></div></article>
    </section>}
    {tab==="connectors"&&<section className="connector-grid">{connectors.map((c,i)=><article className="card connector-card" key={c[0]}><div className="connector-icon">{c[0].slice(0,2).toUpperCase()}</div><span className={`connector-state s${connectorStatus[i]}`}>{statusLabel(connectorStatus[i])}</span><h2>{c[0]}</h2><p>{c[1]}</p><div><span>{t("Възможности","Capabilities")}</span><strong>{c[2]}</strong></div><div className="connector-steps"><i className={connectorStatus[i]!=="available"?"done":""}>1</i><b/><i className={["configuring","tested","active"].includes(connectorStatus[i])?"done":""}>2</i><b/><i className={["tested","active"].includes(connectorStatus[i])?"done":""}>3</i><b/><i className={connectorStatus[i]==="active"?"done":""}>4</i></div><small>{t("Инсталиране · Настройка · Тест · Активиране","Install · Configure · Test · Activate")}</small><button className="secondary-btn" onClick={()=>{advanceConnector(i);notify(connectorStatus[i]==="active"?t("Конекторът е наблюдаван в реално време","Connector is monitored in real time"):t("Преминахте към следващата стъпка","Moved to the next step"));}}>{connectorStatus[i]==="active"?t("Мониторинг","Monitoring"):t("Продължи настройката","Continue setup")}</button></article>)}</section>}
  </>;
}
