"use client";

import { useState } from "react";
import type { UiLanguage } from "../i18n/messages";
import { DataTable, Metric, PanelTitle } from "./shared";

export function Devices({notify,lang}:{notify:(v:string)=>void;lang:UiLanguage}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const [tab,setTab] = useState<"devices"|"points"|"history"|"connectors">("devices");
  const [historyMetric,setHistoryMetric] = useState("active_power");
  const [historyPeriod,setHistoryPeriod] = useState("24h");
  const [historySources,setHistorySources] = useState([true,true,true,false]);
  const [connectorStatus,setConnectorStatus] = useState(["Активен","Активен","Конфигуриране","Наличен"]);
  const devices = [["PV инвертор 01","Deye SUN-50K-SG01HP3","Modbus TCP","Онлайн","48.6 kW","8 сек."],["PV инвертор 02","Sungrow SG125CX-P2","Modbus TCP","Онлайн","72.4 kW","6 сек."],["PV инвертор 03","Huawei SUN2000-100KTL","Modbus TCP","Онлайн","68.8 kW","7 сек."],["PV инвертор 04","Growatt MAX 125KTL3-X","Modbus RTU","Онлайн","58.8 kW","9 сек."],["BESS PCS","TESVOLT TPS-E","Modbus TCP","Онлайн","+41.1 kW","7 сек."],["BMS Controller","Deye BOS-G","CAN / TCP","Онлайн","72% SOC","7 сек."],["Grid meter","Janitza UMG 604","Modbus TCP","Онлайн","−83.2 kW","5 сек."],["Load meter","Schneider PM8000","Modbus TCP","Онлайн","124.3 kW","5 сек."],["EV charger 01","ABB Terra AC","OCPP 1.6","Онлайн","11.0 kW","12 сек."],["EV charger 02","Wallbox Commander","OCPP 1.6","Онлайн","22.0 kW","10 сек."],["Weather station","Kipp & Zonen","RS-485","Внимание","844 W/m²","2 мин."],["Protection relay","Siemens 7SJ82","IEC 61850","Онлайн","Нормално","6 сек."]];
  const metrics = [["active_power","Активна мощност","PV инвертор 01","kW","Изход","48.6","8 сек."],["daily_yield","Енергия днес","PV инвертор 01","kWh","Изход","286.4","8 сек."],["soc","Състояние на заряд","BMS Controller","%","Двупосочна","72.0","7 сек."],["charge_limit","Лимит заряд","BESS PCS","kW","Команда","450","7 сек."],["grid_power","Поток към мрежата","Grid meter","kW","Двупосочна","−83.2","5 сек."],["ev_power_limit","EV мощностен лимит","EV парк","kW","Команда","32.0","12 сек."]];
  const connectors = [["Deye Cloud + Modbus","Инвертори / BMS","Telemetry + control","Активен"],["Sungrow iSolarCloud","Инвертори / BESS","Telemetry + control","Активен"],["Huawei FusionSolar","Инвертори / BESS","Telemetry","Конфигуриране"],["Growatt ShineServer","Инвертори / BESS","Telemetry + control","Наличен"]];
  const advanceConnector=(i:number)=>setConnectorStatus(s=>s.map((x,n)=>n===i?(x==="Наличен"?"Инсталиран":x==="Инсталиран"?"Конфигуриране":x==="Конфигуриране"?"Тест успешен":"Активен"):x));
  const sourceNames=["PV inverter 01","PV inverter 02","BESS PCS","Grid meter"];
  const sourceColours=["solar","blue","green","purple"];
  const historyValues=[[42,38,35,32,34,41,52,68,74,70,63,58],[61,57,52,48,51,59,70,82,89,84,78,72],[26,24,22,20,18,31,47,58,52,43,38,33],[72,68,61,57,60,72,81,93,84,76,70,66]];
  const tabs:[typeof tab,string][]=[["devices",t("Устройства","Devices")],["points",t("Метрични точки","Metric points")],["history",t("Исторически данни","Historical data")],["connectors",t("Конектори","Connectors")]];
  return <>
    <div className="device-toolbar"><div className="searchbox">⌕ <input aria-label={t("Търсене на устройство","Search devices")} placeholder={t("Търсене на устройство...","Search devices...")}/></div><button className="secondary-btn" onClick={()=>notify(t("Сканирането откри 2 нови устройства","Scan found 2 new devices"))}>↻ {t("Открий устройства","Discover devices")}</button><button className="primary-btn" onClick={()=>notify(t("Каталогът е отворен","Catalog opened"))}>+ {t("Добави устройство","Add device")}</button></div>
    <div className="subnav">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==="devices"&&<><section className="kpis compact-kpis"><Metric label={t("Устройства","Devices")} value="12" unit={t("общо","total")} badge="" type="charge"/><Metric label={t("Онлайн","Online")} value="11" unit={t("активни","active")} badge="91.7%" type="spark solar-spark"/><Metric label={t("Комуникация","Communication")} value="98.6" unit="%" badge={t("стабилна","stable")} type="spark load-spark"/><Metric label={t("Последна команда","Latest command")} value="14:31" unit={t("ч.","h")} badge={t("изпълнена","executed")} type="price"/></section><article className="card table-card devices-table"><PanelTitle eyebrow="SCADA / COMMUNICATION" title={t("Всички устройства","All devices")}/><DataTable headers={[t("Устройство","Device"),t("Модел","Model"),t("Протокол","Protocol"),t("Статус","Status"),t("Последни данни","Latest data"),t("Обновено","Updated")]} rows={devices}/></article></>}
    {tab==="points"&&<article className="card table-card metric-table"><PanelTitle eyebrow={t("ЕДИНЕН МОДЕЛ НА ДАННИТЕ","UNIFIED DATA MODEL")} title={t("Метрични точки и права за команда","Metric points and command permissions")} action={<button className="primary-btn" onClick={()=>notify(t("Метричните точки са синхронизирани","Metric points synchronised"))}>{t("Синхронизирай","Synchronise")}</button>}/><DataTable headers={["ID",t("Име","Name"),t("Източник","Source"),t("Единица","Unit"),t("Посока","Direction"),t("Стойност","Value"),t("Обновено","Updated")]} rows={metrics}/><div className="mapping-note"><i>↔</i><span><strong>{t("Нормализация на данните","Data normalisation")}</strong><small>{t("Различните марки се превеждат към общи EMS точки. Командните точки се активират само след проверка на права и безопасни граници.","Different brands are mapped to common EMS points. Command points are enabled only after permission and safety-limit validation.")}</small></span></div></article>}
    {tab==="history"&&<section className="telemetry-history">
      <article className="card telemetry-controls"><PanelTitle eyebrow={t("OPENREMOTE DATAPOINTS","OPENREMOTE DATAPOINTS")} title={t("Сравнение на устройства и измервания","Compare devices and measurements")}/><label><span>{t("Метрика","Metric")}</span><select value={historyMetric} onChange={e=>setHistoryMetric(e.target.value)}><option value="active_power">{t("Активна мощност · kW","Active power · kW")}</option><option value="soc">SOC · %</option><option value="temperature">{t("Температура · °C","Temperature · °C")}</option><option value="energy">{t("Енергия · kWh","Energy · kWh")}</option></select></label><div className="history-source-list">{sourceNames.map((name,i)=><button key={name} className={historySources[i]?`active ${sourceColours[i]}`:""} onClick={()=>setHistorySources(s=>s.map((v,n)=>n===i?!v:v))}><i/>{name}<b>{historySources[i]?"✓":"+"}</b></button>)}</div><small>{t("Изберете няколко източника с еднаква единица за директно сравнение.","Select multiple sources with the same unit for direct comparison.")}</small></article>
      <article className="card telemetry-chart-card"><div className="telemetry-chart-head"><div><p>{t("АКТИВНА МОЩНОСТ ВЪВ ВРЕМЕТО","ACTIVE POWER OVER TIME")}</p><h2>{t("Solar Park East · синхронизирани серии","Solar Park East · synchronised series")}</h2></div><div>{["24h","7d","30d","custom"].map(p=><button key={p} className={historyPeriod===p?"active":""} onClick={()=>setHistoryPeriod(p)}>{p==="custom"?t("Период","Range"):p}</button>)}</div></div><div className="telemetry-chart-grid"><span>125</span><span>100</span><span>75</span><span>50</span><span>25</span><span>0 kW</span><div className="telemetry-bars">{historyValues[0].map((_,hour)=><div className="telemetry-hour" key={hour}>{historyValues.map((series,source)=>historySources[source]&&<i key={source} className={sourceColours[source]} style={{height:`${series[hour]}%`}} title={`${sourceNames[source]} · ${series[hour]} kW`}/>)}<em>{hour%2===0?`${String(hour*2).padStart(2,"0")}:00`:""}</em></div>)}</div></div><div className="telemetry-legend">{sourceNames.map((name,i)=>historySources[i]&&<span key={name}><i className={sourceColours[i]}/>{name}<b>{historyValues[i].at(-1)} kW</b></span>)}</div><div className="data-quality-strip"><span><i>✓</i><b>{t("Пълнота на данните","Data completeness")}</b><strong>99.4%</strong></span><span><i>↻</i><b>{t("Последно обновяване","Last update")}</b><strong>{t("преди 6 сек.","6 sec ago")}</strong></span><span><i>◎</i><b>{t("Резолюция","Resolution")}</b><strong>15 min</strong></span></div></article>
    </section>}
    {tab==="connectors"&&<section className="connector-grid">{connectors.map((c,i)=><article className="card connector-card" key={c[0]}><div className="connector-icon">{c[0].slice(0,2).toUpperCase()}</div><span className={`connector-state s${connectorStatus[i].replace(" ","")}`}>{connectorStatus[i]}</span><h2>{c[0]}</h2><p>{c[1]}</p><div><span>{t("Възможности","Capabilities")}</span><strong>{c[2]}</strong></div><div className="connector-steps"><i className={connectorStatus[i]!=="Наличен"?"done":""}>1</i><b/><i className={["Конфигуриране","Тест успешен","Активен"].includes(connectorStatus[i])?"done":""}>2</i><b/><i className={["Тест успешен","Активен"].includes(connectorStatus[i])?"done":""}>3</i><b/><i className={connectorStatus[i]==="Активен"?"done":""}>4</i></div><small>{t("Инсталиране · Настройка · Тест · Активиране","Install · Configure · Test · Activate")}</small><button className="secondary-btn" onClick={()=>{advanceConnector(i);notify(connectorStatus[i]==="Активен"?t("Конекторът е наблюдаван в реално време","Connector is monitored in real time"):t("Преминахте към следващата стъпка","Moved to the next step"));}}>{connectorStatus[i]==="Активен"?t("Мониторинг","Monitoring"):t("Продължи настройката","Continue setup")}</button></article>)}</section>}
  </>;
}
