"use client";

import { useState } from "react";
import type { UiLanguage } from "../i18n/messages";
import { DataTable, ModeRange, PanelTitle } from "./shared";

export function Gateway({notify,lang}:{notify:(v:string)=>void;lang:UiLanguage}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const [tab,setTab] = useState("Архитектура");
  const [rs485,setRs485] = useState(4);
  const [siteLoad,setSiteLoad] = useState(720);
  const [contractLimit,setContractLimit] = useState(780);
  const [requestedCharge,setRequestedCharge] = useState(100);
  const [emsConnected,setEmsConnected] = useState(true);
  const headroom = Math.max(0,contractLimit-siteLoad);
  const appliedCharge = emsConnected ? Math.min(requestedCharge,headroom) : 0;
  const gatewayDevices = [
    ["PCS","Sinexcel","Modbus TCP · :3200","Heartbeat < 50 s","Онлайн"],
    ["BAU / BMS","261 kWh cabinet","RS485-1 · Modbus RTU","Лимити заряд/разряд","Онлайн"],
    ["PV","Huawei SmartLogger","Ethernet · Modbus TCP","Инвертори + електромери","Онлайн"],
    ["EV","Зарядни станции","RS485-2 / Ethernet","Мощностен лимит","Онлайн"],
    ["Meter","PCC електромер","RS485-3 · Modbus RTU","Обща мощност на обекта","Онлайн"],
    ["I/O","Shelly контролери","Ethernet · локална LAN","Управляеми товари","Онлайн"],
    ["CAN","OLIMEX ESP32-EVB-EA-IND","OT Ethernet · Modbus TCP :1502","Един CAN драйвер на нод","Предвиден"],
    ["RS485","OLIMEX ESP32-EVB-EA-IND","OT Ethernet · Modbus TCP :1502","Външен изолиран RS485 transceiver","Предвиден"],
  ];
  const registerRows = [
    ["40001","site.active_power","kW ×10","Read","PCC meter","0-based → +1"],
    ["40100","bess.soc","% ×10","Read","BAU / BMS","валидирано качество"],
    ["40110","bess.charge_limit","kW ×10","Read","BAU / BMS","фабричен лимит"],
    ["40111","bess.discharge_limit","kW ×10","Read","BAU / BMS","фабричен лимит"],
    ["40200","ems.requested_power","kW ×10","Write","OpenRemote","унифициран знак"],
    ["40201","safe.applied_power","kW ×10","Read","Safety layer","след clamp"],
    ["40900","gateway.status","enum","Read","Local service","online / safe mode"],
  ];
  return <>
    <section className="gateway-hero card"><div className="gateway-ident"><i>⌗</i><div><p>GRIDEX EDGE GATEWAY</p><h2>Един IP. Една регистрова карта. Локална безопасност.</h2><span>Индустриален Modbus концентратор между OpenRemote и разнородния хардуер на обекта.</span></div></div><div className={emsConnected?"gateway-live":"gateway-live safe"}><span>{emsConnected?"EMS връзка активна":"SAFE MODE"}</span><strong>{emsConnected?"Локален контрол работи":"Зададената мощност е 0 kW"}</strong><small>{emsConnected?"Последна команда преди 8 сек.":"Устройствата остават в безопасно състояние"}</small></div></section>
    <section className="gateway-kpis"><div className="card"><span>RS485 портове</span><strong>{rs485}×</strong><small>галванично изолирани</small></div><div className="card"><span>Ethernet</span><strong>2× GbE</strong><small>OT LAN + EMS uplink</small></div><div className="card"><span>Watchdog</span><strong>Hardware</strong><small>автоматично възстановяване</small></div><div className="card"><span>PCS heartbeat</span><strong>35 s</strong><small>локално · рег. 5301</small></div></section>
    <ConfirmedProtocolMaps lang={lang}/>
    <div className="subnav gateway-tabs">{["Архитектура","Хардуерна платформа","Конфигуратор","Регистрова карта","Firmware и safety"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="Конфигуратор"?t("Конфигуратор","Configurator"):x}</button>)}</div>
    {tab==="Архитектура"&&<><article className="card gateway-architecture"><PanelTitle eyebrow="ЮГ → EDGE → СЕВЕР" title="Комуникационна архитектура" action={<span className="pill green">● Локално автономна</span>}/><div className="gateway-flow"><div className="field-devices"><small>ПОЛЕВИ УСТРОЙСТВА</small>{gatewayDevices.map(d=><span key={d[1]}><i>{d[0]}</i><b>{d[1]}</b><em>{d[2]}</em></span>)}</div><b className="flow-arrow">→</b><div className="edge-stack"><small>EDGE КОНЦЕНТРАТОР</small><span><i>1</i><b>Device drivers</b><em>offset · sign · scale · byte order</em></span><span><i>2</i><b>Normalization</b><em>общ модел и quality flags</em></span><span><i>3</i><b>Local services</b><em>heartbeat · cache · timestamps</em></span><span className="safety-layer"><i>4</i><b>Safety envelope</b><em>BMS clamp · software fuse · fail-safe</em></span></div><b className="flow-arrow">→</b><div className="north-stack"><small>OPENREMOTE</small><div><i>OR</i><strong>Modbus TCP Agent</strong><span>Един IP · унифицирана карта</span></div><p><b>Strategy asset</b> пише желана мощност</p><p><b>Control asset</b> получава safe стойност</p></div></div></article><WaveshareTransport mode="path" lang={lang} notify={notify}/><section className="gateway-bottom"><article className="card engineering-rule"><PanelTitle eyebrow="НЕЗАОБИКОЛИМ ПРИНЦИП" title="Стратегията никога не пише директно към инвертора"/><div className="safety-chain"><span><i>1</i><b>Желана мощност</b><small>От арбитраж и график</small></span><em>→</em><span><i>2</i><b>BMS лимити</b><small>Реални, не предполагаеми</small></span><em>→</em><span><i>3</i><b>Software fuse</b><small>Отпусната мощност</small></span><em>→</em><span><i>4</i><b>PCS команда</b><small>Само safe стойност</small></span></div></article><article className="card driver-principle"><PanelTitle eyebrow="ДРАЙВЕР-СЛОЙ" title="Спецификата остава локално"/><ul><li>Положителен/отрицателен знак</li><li>Мащабиране ×10 / ×100</li><li>0-based PDU и +1 offset</li><li>Word и byte order</li><li>Quality и timeout логика</li></ul></article></section></>}
    {tab==="Хардуерна платформа"&&<section className="hardware-grid"><SupportedEdgeHardware lang={lang} notify={notify}/><article className="card hardware-config"><PanelTitle eyebrow="БАЗОВА КОНФИГУРАЦИЯ" title="DIN-rail индустриален контролер"/><div className="hardware-unit"><div className="din-box"><span>GRIDEX</span><strong>EDGE 400</strong><small>24 VDC · DIN rail</small><div>{Array.from({length:rs485}).map((_,i)=><i key={i}>RS{i+1}</i>)}</div><em>LAN 1</em><em>LAN 2</em></div><div className="hardware-specs"><span><b>CPU</b> Radxa ROCK Pi E · RK3328</span><span><b>Мрежа</b> 2× Gigabit Ethernet</span><span><b>RAM / Flash</b> Индустриална microSD / eMMC вариант</span><span><b>Захранване</b> 12 VDC през защитен DC/DC модул</span><span><b>Монтаж</b> DIN rail, индустриален корпус</span></div></div><label className="port-selector"><span>Брой независими RS485 сегменти<strong>{rs485} порта</strong></span><input type="range" min="2" max="6" step="2" value={rs485} onChange={e=>setRs485(Number(e.target.value))}/><small>Всеки порт е галванично изолиран и може да работи с различна скорост, parity и timeout.</small></label></article><article className="card interface-card"><PanelTitle eyebrow="ЗАДЪЛЖИТЕЛНИ ХАРДУЕРНИ ФУНКЦИИ" title="Интерфейси и надеждност"/><div className="interface-list"><span><i>↔</i><b>2–4× изолиран RS485</b><small>Отделяне на BMS, електромери, EV и проблемни шини</small></span><span><i>⌁</i><b>2× Ethernet</b><small>LAN 1: изолирана OT мрежа · LAN 2: EMS/VPN uplink</small></span><span><i>⟳</i><b>Hardware watchdog</b><small>Рестарт при блокирал процес или комуникационен стек</small></span><span><i>⚡</i><b>Захранване и защита</b><small>DC/DC, reverse polarity, surge и brownout recovery</small></span><span><i>◷</i><b>RTC и локален буфер</b><small>Точни timestamp-и и store-and-forward при прекъсване</small></span></div><button className="primary-btn" onClick={()=>notify(`Хардуерният профил с ${rs485} RS485 порта е записан`)}>Запази хардуерния профил</button></article><WaveshareTransport mode="spec" lang={lang} notify={notify}/></section>}
    {tab==="Конфигуратор"&&<EdgeHardwareConfigurator lang={lang} notify={notify}/>}
    {tab==="Регистрова карта"&&<><article className="card table-card register-table"><PanelTitle eyebrow={t("ПРИМЕРНА NORTHBOUND КАРТА · ЗА УТВЪРЖДАВАНЕ","SAMPLE NORTHBOUND MAP · FOR APPROVAL")} title={t("Унифициран Modbus TCP интерфейс към OpenRemote","Unified Modbus TCP interface to OpenRemote")} action={<button className="secondary-btn" onClick={()=>notify(t("Шаблонът на регистровата карта е подготвен","The register-map template is ready"))}>{t("Експорт на шаблон","Export template")}</button>}/><DataTable headers={lang==="en"?["Register","Canonical name","Format","Access","Source","Normalisation"]:["Регистър","Канонично име","Формат","Достъп","Източник","Нормализация"]} rows={registerRows}/></article><div className="register-note" data-no-translate><i>!</i><span><strong>{t("Suntech STE-261L southbound профилът е заключен; показаните 40xxx адреси са работен northbound шаблон.","The Suntech STE-261L southbound profile is locked; the displayed 40xxx addresses are a working northbound template.")}</strong><small>{t("Унифицираната карта към OpenRemote ще се заключи отделно след финалната northbound спецификация и останалите device mappings.","The unified OpenRemote map will be locked separately after the final northbound specification and remaining device mappings.")}</small></span></div></>}
    {tab==="Firmware и safety"&&<><section className="firmware-grid"><article className="card firmware-layers"><PanelTitle eyebrow="FIRMWARE АРХИТЕКТУРА" title="Слоеве с ясна отговорност"/><div><span><i>04</i><b>Northbound Modbus TCP / MQTT</b><small>Унифицирана карта, quality flags, timestamps</small></span><span><i>03</i><b>Safety & command arbiter</b><small>BMS envelope, software fuse, slew/ramp limits</small></span><span><i>02</i><b>Normalization core</b><small>Канонични единици, знак, scale, offset, byte order</small></span><span><i>01</i><b>Device drivers</b><small>Sinexcel, BAU/BMS, Huawei, ai-republic protocol references</small></span><span><i>00</i><b>HAL & transport adapters</b><small>OLIMEX CAN / външен изолиран RS485 · Ethernet · watchdog</small></span></div></article><article className="card state-machine"><PanelTitle eyebrow="STATE MACHINE" title="Първо комуникация, после мощност"/><div><span className="done">Boot</span><i>→</i><span className="done">Comms OK</span><i>→</i><span className="done">BMS limits valid</span><i>→</i><span className={emsConnected?"active":""}>{emsConnected?"Ready":"Safe mode"}</span></div><ul><li>Без валидни BMS лимити няма enable.</li><li>Heartbeat към PCS се поддържа локално.</li><li>Загуба на EMS връзка → setpoint 0 kW.</li><li>OLIMEX нодът е device driver boundary; ROCK Pi E е safety controller.</li></ul><button className={emsConnected?"secondary-btn danger":"primary-btn"} onClick={()=>setEmsConnected(!emsConnected)}>{emsConnected?"Симулирай загуба на EMS":"Възстанови EMS връзката"}</button></article></section><article className="card fuse-simulator"><PanelTitle eyebrow="ЛОКАЛЕН SOFTWARE FUSE" title="Клампване спрямо отпуснатата мощност" action={<span className={appliedCharge===requestedCharge?"pill green":"pill amber-pill"}>{appliedCharge===requestedCharge?"Без ограничение":"Командата е ограничена"}</span>}/><div className="fuse-grid"><ModeRange label="Текущ товар на обекта" value={siteLoad} unit="kW" min={300} max={900} onChange={setSiteLoad}/><ModeRange label="Отпусната мощност" value={contractLimit} unit="kW" min={500} max={1000} onChange={setContractLimit}/><ModeRange label="Заявено зареждане BESS" value={requestedCharge} unit="kW" min={0} max={300} onChange={setRequestedCharge}/><div className="fuse-result"><span><small>Свободен капацитет</small><strong>{headroom} kW</strong></span><i>→</i><span><small>Приложена команда</small><strong>{appliedCharge} kW</strong></span><p>{!emsConnected?"EMS връзката липсва — fail-safe нулира командата.":appliedCharge<requestedCharge?`Заявката е клампната от ${requestedCharge} на ${appliedCharge} kW.`:"Командата е в безопасния envelope."}</p></div></div></article></>}
  </>;
}

type EdgeGatewayStage = "draft"|"compiled"|"installed";

type EdgeGatewayDraft = { id:string; hardware:"olimexIndustrial"|"olimexLab"; deviceType:string; modelId:string; channel:string; address:string; stage:EdgeGatewayStage };

function EdgeHardwareConfigurator({lang,notify}:{lang:UiLanguage;notify:(v:string)=>void}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const deviceTypes=[
    {id:"inverter",label:t("Инвертор / PCS","Inverter / PCS"),icon:"↗"},
    {id:"battery",label:t("Батерия / BMS","Battery / BMS"),icon:"▣"},
    {id:"meter",label:t("Смарт електромер","Smart meter"),icon:"⌁"},
    {id:"evse",label:t("Зарядна станция","EV charger"),icon:"ϟ"},
    {id:"io",label:t("Управляем товар / I/O","Controllable load / I/O"),icon:"⌘"},
  ];
  const models=[
    {id:"deye-modbus",type:"inverter",label:"Deye · Modbus inverter",interfaces:["RS485"],driver:"gridex.deye.modbus",quality:t("R&D карта · тест по модел","R&D map · model test required")},
    {id:"huawei-modbus",type:"inverter",label:"Huawei · SmartLogger / inverter",interfaces:["RS485"],driver:"gridex.huawei.modbus",quality:t("R&D карта · тест по модел","R&D map · model test required")},
    {id:"growatt-modbus",type:"inverter",label:"Growatt · Modbus inverter",interfaces:["RS485"],driver:"gridex.growatt.modbus",quality:t("R&D карта · тест по модел","R&D map · model test required")},
    {id:"pylontech-can",type:"battery",label:"Pylontech · CAN BMS",interfaces:["CAN"],driver:"gridex.pylontech.can",quality:t("Публична протоколна референция","Public protocol reference")},
    {id:"byd-can",type:"battery",label:"BYD · CAN BMS",interfaces:["CAN"],driver:"gridex.byd.can",quality:t("Публична протоколна референция","Public protocol reference")},
    {id:"bcq-261-rtu",type:"battery",label:"Suntech 261 · BCQ BMS",interfaces:["RS485"],driver:"gridex.suntech261.bcq",quality:t("Документ наличен · commissioning тест","Document available · commissioning test")},
    {id:"eastron-meter",type:"meter",label:"Eastron · SDM Modbus meter",interfaces:["RS485"],driver:"gridex.eastron.sdm",quality:t("Драйверен шаблон","Driver template")},
    {id:"huawei-meter",type:"meter",label:"Huawei · DTSU meter",interfaces:["RS485"],driver:"gridex.huawei.dtsu",quality:t("Драйверен шаблон","Driver template")},
    {id:"modbus-evse",type:"evse",label:t("Modbus EVSE · модел при commissioning","Modbus EVSE · model at commissioning"),interfaces:["RS485"],driver:"gridex.evse.modbus",quality:t("Изисква карта за точния модел","Exact model map required")},
    {id:"can-io",type:"io",label:t("CAN I/O модул · индустриален","Industrial CAN I/O module"),interfaces:["CAN"],driver:"gridex.io.can",quality:t("Изисква карта за точния модел","Exact model map required")},
  ];
  const hardware={
    olimexIndustrial:{label:"OLIMEX ESP32-EVB-EA-IND",channels:["CAN","RS485"]},
    olimexLab:{label:"OLIMEX ESP32-EVB (lab)",channels:["CAN","RS485"]},
  };
  const [gateways,setGateways]=useState<EdgeGatewayDraft[]>([
    {id:"GW-01",hardware:"olimexIndustrial",deviceType:"inverter",modelId:"deye-modbus",channel:"RS485",address:"1",stage:"draft"},
    {id:"GW-02",hardware:"olimexIndustrial",deviceType:"battery",modelId:"pylontech-can",channel:"CAN",address:"0x351",stage:"draft"},
  ]);
  const modelFor=(gateway:EdgeGatewayDraft)=>models.find(model=>model.id===gateway.modelId)||models.find(model=>model.type===gateway.deviceType)!;
  const compatibleChannels=(gateway:EdgeGatewayDraft,model=modelFor(gateway))=>hardware[gateway.hardware].channels.filter(channel=>model.interfaces.some(protocol=>channel.startsWith(protocol)));
  const updateGateway=(id:string,patch:Partial<EdgeGatewayDraft>)=>setGateways(current=>current.map(gateway=>{
    if(gateway.id!==id)return gateway;
    const next={...gateway,...patch,stage:"draft" as EdgeGatewayStage};
    if(patch.deviceType){const first=models.find(model=>model.type===patch.deviceType)!;next.modelId=first.id;const allowed=hardware[next.hardware].channels.filter(channel=>first.interfaces.some(protocol=>channel.startsWith(protocol)));next.channel=allowed[0]||"";next.address=first.interfaces[0]==="CAN"?"0x351":"1";}
    if(patch.hardware||patch.modelId){const selected=models.find(model=>model.id===next.modelId)!;const allowed=hardware[next.hardware].channels.filter(channel=>selected.interfaces.some(protocol=>channel.startsWith(protocol)));if(!allowed.includes(next.channel))next.channel=allowed[0]||"";}
    return next;
  }));
  const addGateway=()=>setGateways(current=>{const number=Math.max(0,...current.map(item=>Number(item.id.replace("GW-",""))))+1;return [...current,{id:`GW-${String(number).padStart(2,"0")}`,hardware:"olimexIndustrial",deviceType:"meter",modelId:"eastron-meter",channel:"RS485",address:"1",stage:"draft"}];});
  const setStage=(id:string,stage:EdgeGatewayStage)=>{setGateways(current=>current.map(gateway=>gateway.id===id?{...gateway,stage}:gateway));notify(stage==="compiled"?t(`Драйверът за ${id} е компилиран`,`Driver for ${id} compiled`):t(`Драйверът за ${id} е инсталиран`,`Driver for ${id} installed`));};
  const installed=gateways.filter(gateway=>gateway.stage==="installed").length;
  return <section className="edge-configurator" data-no-translate>
    <article className="card edge-config-head"><div><p>{t("КОНФИГУРАЦИЯ ПО ГЕЙТ","PER-GATE CONFIGURATION")}</p><h2>{t("Един управляващ модул + отделен гейт за всяко устройство","One control module + a separate gateway for every device")}</h2><span>{t("Всеки гейт обслужва точно 1 устройство от 1 тип, бранд и модел. Смесването на продукти върху един гейт е блокирано.","Each gateway serves exactly 1 device of 1 type, brand and model. Mixing products on one gateway is blocked.")}</span></div><button className="primary-btn" onClick={addGateway}>+ {t("Добави гейт","Add gateway")}</button></article>
    <article className="card controller-module"><i>R</i><div><small>{t("УПРАВЛЯВАЩ МОДУЛ · ФИКСИРАН","CONTROL MODULE · FIXED")}</small><strong>Radxa ROCK Pi E · RK3328</strong><span>{t("LAN 1: OT / Modbus TCP · LAN 2: WAN / VPN / OpenRemote · управлява всички гейтове","LAN 1: OT / Modbus TCP · LAN 2: WAN / VPN / OpenRemote · controls all gateways")}</span></div><em>1×</em><b>● {t("Активен","Active")}</b></article>
    <div className="gateway-config-summary"><span><small>{t("Конфигурирани гейтове","Configured gateways")}</small><strong>{gateways.length}</strong></span><span><small>{t("Инсталирани драйвери","Installed drivers")}</small><strong>{installed} / {gateways.length}</strong></span><span><small>{t("Правило","Rule")}</small><strong>1 gate = 1 device</strong></span><span><small>{t("Разрешени шини","Allowed buses")}</small><strong>CAN · RS485</strong></span></div>
    <div className="gateway-config-list">{gateways.map(gateway=>{const model=modelFor(gateway);const channels=compatibleChannels(gateway,model);const target=t("ESP32-EVB firmware на нода","ESP32-EVB node firmware");return <article className="card gateway-config-card" key={gateway.id}>
      <header><div><i>{gateway.id.replace("GW-","")}</i><span><small>{t("DEVICE GATEWAY","DEVICE GATEWAY")}</small><strong>{gateway.id}</strong></span></div><em className={`gateway-stage ${gateway.stage}`}>{gateway.stage==="draft"?t("За компилация","Ready to compile"):gateway.stage==="compiled"?t("Компилиран","Compiled"):t("Инсталиран","Installed")}</em><button aria-label={t(`Премахни ${gateway.id}`,`Remove ${gateway.id}`)} onClick={()=>setGateways(current=>current.filter(item=>item.id!==gateway.id))}>×</button></header>
      <div className="gateway-config-fields">
        <label><span>{t("Хардуер на гейта","Gateway hardware")}</span><select value={gateway.hardware} onChange={e=>updateGateway(gateway.id,{hardware:e.target.value as EdgeGatewayDraft["hardware"]})}><option value="olimexIndustrial">{hardware.olimexIndustrial.label}</option><option value="olimexLab">{hardware.olimexLab.label}</option></select></label>
        <label><span>{t("Тип устройство","Device type")}</span><select value={gateway.deviceType} onChange={e=>updateGateway(gateway.id,{deviceType:e.target.value})}>{deviceTypes.map(type=><option value={type.id} key={type.id}>{type.icon} {type.label}</option>)}</select></label>
        <label><span>{t("Марка и модел · 1 брой","Brand and model · quantity 1")}</span><select value={gateway.modelId} onChange={e=>updateGateway(gateway.id,{modelId:e.target.value})}>{models.filter(item=>item.type===gateway.deviceType).map(item=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label>
        <label><span>{t("Свързан интерфейс","Connected interface")}</span><select value={gateway.channel} onChange={e=>updateGateway(gateway.id,{channel:e.target.value})}>{channels.map(channel=><option value={channel} key={channel}>{channel}</option>)}</select></label>
        <label><span>{model.interfaces[0]==="CAN"?"CAN ID":t("Modbus адрес","Modbus address")}</span><input value={gateway.address} onChange={e=>updateGateway(gateway.id,{address:e.target.value})}/></label>
      </div>
      <div className="gateway-driver-plan"><span><small>{t("Драйверен пакет","Driver package")}</small><strong>{model.driver}</strong><em>{model.quality}</em></span><b>→</b><span><small>{t("Цел за инсталиране","Installation target")}</small><strong>{target}</strong><em>{t("Отделна компилация само за избрания продукт","Separate build for the selected product only")}</em></span></div>
      <div className="gateway-admin-actions"><span><i>!</i><small>{t("Само администратор може да компилира и инсталира драйвера. Всяка промяна връща конфигурацията в статус „За компилация“.","Only an administrator can compile and install the driver. Any change returns the configuration to Ready to compile.")}</small></span><button className="secondary-btn" disabled={gateway.stage!=="draft"} onClick={()=>setStage(gateway.id,"compiled")}>{t("Компилирай драйвер","Compile driver")}</button><button className="primary-btn" disabled={gateway.stage!=="compiled"} onClick={()=>setStage(gateway.id,"installed")}>{t("Инсталирай на гейта","Install on gateway")}</button></div>
    </article>})}</div>
    <div className="register-note"><i>!</i><span><strong>{t("Ограничение за първата версия: без смесени брандове и типове върху един гейт.","Initial-release constraint: no mixed brands or device types on one gateway.")}</strong><small>{t("Ако обектът има два инвертора или две батерии, всеки физически продукт получава собствен гейт и собствен драйверен build.","If a site has two inverters or two batteries, each physical product receives its own gateway and its own driver build.")}</small></span></div>
  </section>;
}

function ConfirmedProtocolMaps({lang}:{lang:UiLanguage}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const confirmed=[
    {brand:"Suntech",model:"SunPro / SunStorage Pro 261",type:t("All-in-one BESS · 261 kWh","All-in-one BESS · 261 kWh"),protocol:"Modbus TCP · :3200 · Unit 1",scope:t("ABCD Int32, FC04 telemetry, FC06 commands, heartbeat и BMS safety","ABCD Int32, FC04 telemetry, FC06 commands, heartbeat and BMS safety"),status:t("Потвърдено с производителя","Manufacturer-confirmed")},
    {brand:"Sinexcel",model:t("PCS в конфигурацията 261","PCS in the 261 configuration"),type:"PCS / bidirectional inverter",protocol:"Modbus TCP · port 3200",scope:t("P/Q ×10, readiness, BMS limits, heartbeat 5301/5302","P/Q ×10, readiness, BMS limits, heartbeat 5301/5302"),status:t("Потвърдено с производителя","Manufacturer-confirmed")},
    {brand:"BCQ",model:t("Контролер за 261 kWh шкаф","261 kWh cabinet controller"),type:"Cabinet EMS / BMS gateway",protocol:"Modbus register map",scope:t("SOC, статуси, аларми, ограничения заряд/разряд","SOC, status, alarms, charge/discharge limits"),status:t("Документ наличен","Document available")},
  ];
  const publicMaps=["Deye","GoodWe","Growatt","Huawei","LuxPower","Pylontech","SMA","Sol-Ark","Solis","BYD","Daly","JBD","JK","Narada","PACE","Seplos"];
  return <article className="card confirmed-protocols" data-no-translate>
    <div className="confirmed-protocols-head"><div><p>{t("КОМУНИКАЦИОННИ КАРТИ","COMMUNICATION MAPS")}</p><h2>{t("Потвърдени интеграции и налични протоколни референции","Confirmed integrations and available protocol references")}</h2><span>{t("Ясно отделяме проектно потвърдените карти от публичните R&D протоколи, които изискват тест с точния модел и firmware.","Project-confirmed maps are clearly separated from public R&D protocols that require testing with the exact model and firmware.")}</span></div><span className="confirmed-badge"><i>✓</i><b>3</b><small>{t("проектни карти","project maps")}</small></span></div>
    <div className="confirmed-map-grid">{confirmed.map(item=><section key={`${item.brand}-${item.model}`}><header><span>{item.brand}</span><em>{item.status}</em></header><h3>{item.model}</h3><p>{item.type}</p><dl><div><dt>{t("Протокол","Protocol")}</dt><dd>{item.protocol}</dd></div><div><dt>{t("Обхват","Scope")}</dt><dd>{item.scope}</dd></div></dl></section>)}</div>
    <section className="suntech-confirmed-profile"><header><div><p>SUNTECH STE-261L · MODBUS TCP</p><h3>{t("Заключен драйверен профил","Locked driver profile")}</h3><span>{t("Отговорите на производителя са нанесени в ROCK Pi E C++ драйвера.","The manufacturer's clarifications are implemented in the ROCK Pi E C++ driver.")}</span></div><em><i>✓</i>{t("ПОТВЪРДЕН","CONFIRMED")}</em></header><div className="suntech-confirmed-grid"><span><small>{t("КОДИРАНЕ","ENCODING")}</small><strong>ABCD · Int32 ÷10</strong><em>{t("High word first · signed","High word first · signed")}</em></span><span><small>{t("БРОЯЧИ","COUNTERS")}</small><strong>FC04 · 122–125</strong><em>{t("Един атомарен прочит","One atomic read")}</em></span><span><small>HEARTBEAT</small><strong>5302 → 5301</strong><em>FC06 · 60 s / refresh 35 s</em></span><span><small>{t("МОЩНОСТ","POWER")}</small><strong>FC06 · reg. 5005</strong><em>{t("+ разряд · − заряд","+ discharge · − charge")}</em></span><span><small>{t("BMS ЛИМИТИ","BMS LIMITS")}</small><strong>127 / 128 · 1–2 s</strong><em>{t("0 kW забранява посоката","0 kW prohibits direction")}</em></span><span><small>{t("SAFETY GATE","SAFETY GATE")}</small><strong>5001 / 5002 / 5003</strong><em>{t("Fault + SOC + fresh limits","Fault + SOC + fresh limits")}</em></span><span><small>{t("КОМУНИКАЦИЯ","COMMUNICATION")}</small><strong>:3200 · Unit 1</strong><em>{t("Poll 0.5–1 s · timeout 3–5 s","Poll 0.5–1 s · timeout 3–5 s")}</em></span><span><small>{t("ДНЕВЕН RESET","DAILY RESET")}</small><strong>129 / 130 · 00:00</strong><em>{t("Локален BMS RTC","Local BMS RTC")}</em></span></div></section>
    <div className="public-map-strip"><div><strong>{t("Публични карти / R&D референции","Public maps / R&D references")}</strong><small>{t("Налични за разработка на собствен GrideX драйвер; не означава сертифицирана съвместимост за всеки модел.","Available for original GrideX driver development; this does not mean certified compatibility with every model.")}</small></div><div>{publicMaps.map(brand=><span key={brand}>{brand}</span>)}</div></div>
  </article>;
}

function SupportedEdgeHardware({lang}:{lang:UiLanguage}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const hardware=[
    {kind:t("УПРАВЛЯВАЩ МОДУЛ","CONTROL MODULE"),icon:"R",name:"Radxa ROCK Pi E",status:t("Основен контролер","Primary controller"),summary:t("Linux мозъкът на Edge решението с отделени OT и WAN мрежи.","The Linux brain of the Edge solution with separated OT and WAN networks."),features:["RK3328 · 4-core ARM",t("2× Gigabit Ethernet: OT + WAN към Site Router","2× Gigabit Ethernet: OT + WAN to Site Router"),t("Polling, normalization, safety и локален buffer","Polling, normalization, safety and local buffer"),t("Private MQTT bridge · HTTPS · Modbus TCP","Private MQTT bridge · HTTPS · Modbus TCP")]},
    {kind:t("ИНДУСТРИАЛЕН DEVICE NODE","INDUSTRIAL DEVICE NODE"),icon:"O",name:"OLIMEX ESP32-EVB-EA-IND",status:t("Производствен нод","Production node"),summary:t("Един ESP32 Ethernet нод с конкретен драйвер за един инвертор, BMS, електромер или EVSE.","One Ethernet ESP32 node with a dedicated driver for one inverter, BMS, meter or EVSE."),features:["100 Mbps Ethernet · ESP32",t("1× CAN + UEXT за външен изолиран RS485","1× CAN + UEXT for external isolated RS485"),t("Modbus TCP :1502 към ROCK Pi E","Modbus TCP :1502 to ROCK Pi E"),t("VPN-only MQTT telemetry през site router","VPN-only MQTT telemetry via site router")]},
    {kind:t("ЛАБОРАТОРЕН DEVICE NODE","LAB DEVICE NODE"),icon:"O",name:"OLIMEX ESP32-EVB",status:t("Прототипиране","Prototyping"),summary:t("Същата firmware основа за bench тестове; production профилът използва индустриалния EA-IND вариант.","The same firmware baseline for bench tests; production uses the industrial EA-IND variant."),features:["ESP32-EVB board profile",t("CAN или външен изолиран RS485","CAN or external isolated RS485"),t("Ограничен до един тип устройство","Limited to one device type"),t("Без WireGuard на нода","No WireGuard on the node")]},
  ];
  return <article className="card edge-hardware-suite" data-no-translate><div className="edge-hardware-title"><div><p>{t("ПОДДЪРЖАНО ЦЯЛОСТНО РЕШЕНИЕ","SUPPORTED END-TO-END SOLUTION")}</p><h2>{t("Две хардуерни роли в GrideX Edge","Two hardware roles in GrideX Edge")}</h2><span>{t("ROCK Pi E управлява и прилага safety; всеки OLIMEX ESP32-EVB нод държи конкретния CAN или RS485 драйвер за един продукт.","ROCK Pi E controls and applies safety; every OLIMEX ESP32-EVB node holds the dedicated CAN or RS485 driver for one product.")}</span></div><div className="hardware-role-flow"><b>ROCK Pi E</b><i>↔</i><b>OT Ethernet</b><i>↔</i><b>OLIMEX node</b></div></div><div className="edge-hardware-cards">{hardware.map(item=><section key={item.name}><header><i>{item.icon}</i><span><small>{item.kind}</small><strong>{item.name}</strong></span><em>{item.status}</em></header><p>{item.summary}</p><ul>{item.features.map(feature=><li key={feature}>✓ {feature}</li>)}</ul></section>)}</div><button className="primary-btn edge-hardware-action" onClick={()=>notify(t("Цялостният Edge хардуерен профил е избран","The complete Edge hardware profile is selected"))}>{t("Избери цялостното решение","Select the complete solution")}</button></article>;
}

function WaveshareTransport({mode,lang}:{mode:"path"|"spec";lang:UiLanguage}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  if(mode==="path") return <article className="card waveshare-path" data-no-translate>
    <div className="waveshare-path-head"><div><p>{t("УСТРОЙСТВЕН EDGE НОД","DEVICE EDGE NODE")}</p><h2>OLIMEX ESP32-EVB-EA-IND</h2><span>{t("Един Ethernet ESP32 нод за един продукт: CAN или външен изолиран RS485 към устройството; Modbus TCP към ROCK Pi E.","One Ethernet ESP32 node per product: CAN or externally isolated RS485 to the device; Modbus TCP to ROCK Pi E.")}</span></div><a href="https://github.com/OLIMEX/ESP32-EVB" target="_blank" rel="noreferrer">OLIMEX ↗</a></div>
    <div className="waveshare-flow"><span><i>CAN / RS485</i><b>{t("Едно устройство","One device")}</b></span><em>→</em><strong><small>OLIMEX ESP32-EVB</small>{t("Локален драйвер","Local driver")}</strong><em>→</em><strong><small>OT ETHERNET</small>Modbus TCP :1502</strong><em>→</em><strong><small>ROCK Pi E</small>{t("Safety + команда","Safety + command")}</strong></div>
    <div className="transport-rule"><i>!</i><span><strong>{t("ROCK Pi E чете телеметрията от нода по OT Modbus TCP и само той я публикува към private MQTT; управляващите команди винаги минават през него.","ROCK Pi E reads node telemetry over OT Modbus TCP and alone publishes it to private MQTT; control commands always pass through it.")}</strong><small>{t("Нодът няма WireGuard, MQTT credentials или команди от интернет. Site Router предоставя VPN тунела за ROCK Pi E.","The node has no WireGuard, MQTT credentials or internet commands. The Site Router provides the VPN tunnel for ROCK Pi E.")}</small></span></div>
  </article>;
  return <article className="card waveshare-spec" data-no-translate><div className="waveshare-product"><div className="waveshare-product-mark"><small>OLIMEX</small><strong>EVB</strong><span>CAN / 485</span></div><div><p>{t("ИЗБРАН УСТРОЙСТВЕН НОД","SELECTED DEVICE NODE")}</p><h2>ESP32-EVB-EA-IND</h2><span>{t("Индустриален Ethernet нод с CAN и UEXT UART за външен изолиран RS485 transceiver.","Industrial Ethernet node with CAN and UEXT UART for an external isolated RS485 transceiver.")}</span></div><a href="https://www.olimex.com/Products/IoT/ESP32/ESP32-EVB-EA-IND/open-source-hardware" target="_blank" rel="noreferrer">{t("Технически данни ↗","Technical data ↗")}</a></div><div className="waveshare-spec-grid"><span><small>Ethernet</small><strong>100 Mbps</strong><em>OT network · Modbus TCP :1502</em></span><span><small>CAN</small><strong>1 × CAN</strong><em>One driver build per connected device</em></span><span><small>RS485</small><strong>{t("Външен изолиран transceiver","External isolated transceiver")}</strong><em>UEXT UART · per-device profile</em></span><span><small>MQTT</small><strong>VPN-only telemetry</strong><em>{t("През site router","Via site router")}</em></span><span><small>{t("Команди","Commands")}</small><strong>ROCK Pi E only</strong><em>{t("Мрежова allowlist","Network allowlist")}</em></span><span><small>Safety</small><strong>TTL + safe zero</strong><em>{t("При невалидна или остаряла команда","On invalid or stale command")}</em></span></div></article>;
}
