import { useEffect } from 'react';
import type { UiLanguage } from '../i18n/messages';
import { documentationLink } from '../lib/documentation';
import { sectionHref } from '../lib/routes';

export function ProfileHelp({lang,live}:{lang:UiLanguage;live:boolean}) {
  const t=(bg:string,en:string)=>lang==='en'?en:bg;
  useEffect(()=>{
    const id=decodeURIComponent(window.location.hash.slice(1));
    if(!id)return;
    const frame=requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({block:'start'}));
    return()=>cancelAnimationFrame(frame);
  },[]);
  return <div className="profile-help-page" data-no-translate>
    <section className="card profile-help-intro">
      <div><span className="profile-kicker">GRIDEX · {t('ПОМОЩ','HELP')}</span><h2>{t('Достъп до GrideX и профил','GrideX access and profile')}</h2><p>{t('Реалният достъп е само с покана. Тук са описани организациите, ролите, приемането на покана и настройките на профила.','Live access is by invitation only. This guide explains organisations, roles, invitation acceptance and profile settings.')}</p></div>
      <a className="profile-action primary" href={sectionHref('profile','',!live)}>{t('Към моя профил','Open my profile')} <span aria-hidden="true">↗</span></a>
    </section>
    <nav className="profile-help-index card" aria-label={t('Раздели на документацията','Guide sections')}>
      <a href="#getting-started">{t('Как се получава достъп','How to get access')}</a><a href="#organisations">{t('Организации и права','Organisations and rights')}</a><a href="#invite-members">{t('Покана на колега','Invite a colleague')}</a><a href="#devices-and-sites">{t('Обекти и устройства','Sites and devices')}</a><a href="#identity">{t('Идентичност','Identity')}</a><a href="#access">{t('Роля и обекти','Role and Sites')}</a><a href="#services">{t('Заявки за услуги','Service requests')}</a><a href="#email-notifications">{t('Имейл известия','Email notifications')}</a><a href="#session">{t('Сесия и изход','Session and sign-out')}</a>
    </nav>
    <div className="profile-help-grid">
      <article id="getting-started" className="card profile-help-topic"><span>{t('НАЧАЛО','START')}</span><h3>{t('Нужна Ви е покана','You need an invitation')}</h3><p>{t('Демото е достъпно без вход, но не дава достъп до реални данни. За реален акаунт първият администратор на нова организация получава покана от администратора на платформата. След това администраторът на организацията кани своите колеги. Не можете сами да се регистрирате като администратор чрез бутона „Вход“. Ако нямате покана, обърнете се към администратора на Вашата организация.','The demo is available without signing in, but it does not grant access to live data. The first administrator of a new organisation receives an invitation from the platform administrator. That organisation administrator can then invite colleagues. The Sign in button does not self-register administrators. If you have no invitation, contact your organisation administrator.')}</p></article>
      <article id="organisations" className="card profile-help-topic"><span>{t('ОРГАНИЗАЦИИ','ORGANISATIONS')}</span><h3>{t('Покана и обхват на правата','Invitation and access scope')}</h3><p>{t('Първият администратор на нова организация следва линка в поканата, потвърждава имейла, задава парола и влиза. Порталът завършва точно тази покана автоматично след проверка от сървъра — няма втори бутон за приемане. При грешка поканата остава чакаща; обновете екрана или потърсете администратора. Поканите за колеги в съществуваща организация засега се приемат в „Профил“. Всяка организация има отделно пространство и вижда само разрешените Обекти.','The first administrator of a new organisation follows the invitation link, verifies email, sets a password and signs in. The portal completes that exact invitation after server verification; there is no second acceptance button. On failure the invitation remains pending; refresh or contact the administrator. Invitations for colleagues in an existing organisation are still accepted in Profile. Each organisation has a separate space and sees only authorised Sites.')}</p></article>
      <article id="invite-members" className="card profile-help-topic"><span>{t('ЗА АДМИНИСТРАТОР НА ОРГАНИЗАЦИЯ','FOR AN ORGANISATION ADMINISTRATOR')}</span><h3>{t('Поканете колега във Вашата организация','Invite a colleague into your organisation')}</h3>
        <p>{t('Това е покана за потребител на вече съществуваща организация, не за създаване на нова организация.','This invites a member into an existing organisation; it does not create a new organisation.')}</p>
        <ol>
          <li>{t('Отворете „Клиенти и договори → Потребители и покани“ и изберете своята организация.','Open Customers & contracts → Users & invitations and select your organisation.')}</li>
          <li>{t('Въведете имейла, изберете роля и маркирайте само нужните Обекти. Без избран Обект поканата не дава достъп до Обекти.','Enter the email, choose a role and select only the required Sites. With no Site selected, the invitation grants no Site access.')}</li>
          <li>{t('Натиснете „Изпрати покана“. Потвърденото изпращане се показва на екрана и в „Изпратени от Вас покани“ след обновяване. Само покана със статус sent може да се изпрати наново; при неясна доставка проверете статуса, без сляпо повторение.','Select Send invitation. Confirmed dispatch appears on screen and in Invitations sent by you after refresh. Only a sent invitation can be resent; inspect an uncertain status instead of retrying blindly.')}</li>
          <li>{t('Колегата потвърждава имейла, задава парола и приема поканата от „Профил“. Едва тогава проверете разрешените му Обекти.','Your colleague verifies the email, sets a password and accepts the invitation in Profile. Only then verify their permitted Sites.')}</li>
        </ol>
        <p>{t('Тази форма не дава роля „Администратор на организация“. Наблюдателят не вижда административните „Клиенти и договори“ и „Потребители и покани“.','This form cannot grant the Organisation administrator role. A Viewer does not see the administrative Customers & contracts or Users & invitations sections.')}</p>
        <a href={`${documentationLink('members',lang).href}#invite-a-colleague`} target="_blank" rel="noopener noreferrer">{t('Подробно ръководство','Detailed guide')} <span aria-hidden="true">↗</span></a>
      </article>
      <article id="devices-and-sites" className="card profile-help-topic"><span>{t('ОБЕКТИ И УСТРОЙСТВА','SITES AND DEVICES')}</span><h3>{t('Кой създава, настройва и пуска','Who creates, configures and activates')}</h3>
        <p>{t('Обект и ново ROCK Pi E или ESP32 устройство създава само администраторът на организацията през „Обекти“ и „Устройства“. Те се потвърждават в OpenRemote. Одобрен потребител вижда само разрешения му Обект; интеграторът и администраторът могат да подготвят до две роли като чернова. Пускането в работа засега е само от администратора и не става при самото добавяне.', 'Only the organisation administrator creates a Site and new ROCK Pi E or ESP32 device through Sites and Devices. They are verified in OpenRemote. An approved member sees only authorised Sites; the integrator and administrator may draft up to two roles. Activation remains administrator-only and is not triggered by adding a device.')}</p>
        <a href={`${documentationLink('members',lang).href}#sites-and-devices`} target="_blank" rel="noopener noreferrer">{t('Пълен процес и текущо състояние','Full process and current status')} <span aria-hidden="true">↗</span></a>
      </article>
      <article id="identity" className="card profile-help-topic"><span>01 / {t('ПРОФИЛ','PROFILE')}</span><h3>{t('Име и имейл','Name and email')}</h3><p>{t('Показват се данните от удостоверения Ви GrideX/Keycloak профил. Не въвеждате парола на тази страница. Имейлът за известия се взема само от потвърдената идентичност.','These values come from your authenticated GrideX/Keycloak account. You do not enter a password here. Notification email is taken only from a verified identity.')}</p></article>
      <article id="access" className="card profile-help-topic"><span>02 / {t('ДОСТЪП','ACCESS')}</span><h3>{t('Роля и обекти','Role and Sites')}</h3><p>{t('Ролята описва предоставените Ви права. „Моите обекти“ показва обектите, до които имате достъп; тя не е настройка за получаване на известия. Правата за конкретен обект се проверяват от backend и OpenRemote преди изпращане на имейл.','Your role describes your permissions. “My Sites” shows the Sites you can access; it is not a notification setting. Site access is checked by the backend and OpenRemote before an email is sent.')}</p></article>
      <article id="services" className="card profile-help-topic"><span>03 / {t('УСЛУГИ','SERVICES')}</span><h3>{t('Заявка и две одобрения','Request and two approvals')}</h3><p>{t('В „Профил → Услуги“ виждате петте услуги. Засега се заявяват само „Цени ден напред“ с избор България/BG и „Графики“ — отделно. Заявката не включва достъп. Първо супер администраторът разрешава организацията и BG зоната, после нейният администратор разрешава конкретния потребител. Статусът и историята са видими до услугата.','Profile → Services shows five services. Currently only Day-ahead prices with Bulgaria/BG and Visualisations can be requested separately. A request grants no access. The platform administrator first enables the organisation and BG zone; its administrator then enables the specific member. Status and history are shown with the service.')}</p><a href={documentationLink('members',lang).href+'#additional-services'} target="_blank" rel="noopener noreferrer">{t('Пълно ръководство','Full guide')} ↗</a></article>
      <article id="email-notifications" className="card profile-help-topic"><span>03 / {t('ИЗВЕСТИЯ','NOTIFICATIONS')}</span><h3>{t('Какво прави отметката','What the checkbox does')}</h3><p>{t('„Получавай имейл за всички бъдещи събития“ е Ваш постоянен избор, изключен по подразбиране. Включването не изпраща писма за минали събития и не изисква одобрение за всяко следващо. Засега е свързано единствено прекъсването на heartbeat: един имейл за прекъсване, нов само след възстановяване и ново прекъсване. Следващите видове събития ще използват същия избор, след като бъдат внедрени.','“Email me about all future events” is your persistent preference, off by default. Enabling it does not send messages for past events or require approval for each future event. Currently only missed heartbeat is connected: one email per outage, and another only after recovery and a new outage. Future event types will use the same choice once implemented.')}</p></article>
      <article id="session" className="card profile-help-topic"><span>04 / {t('СИГУРНОСТ','SECURITY')}</span><h3>{t('Сесия и изход','Session and sign-out')}</h3><p>{t('При временно недостъпна проверка порталът опитва отново автоматично, без да Ви отписва или показва демо данни. „Изход“ прекратява сесията в този браузър. Ако достъпът изтече или бъде отнет, ще е нужен нов вход; това не променя предпочитанието Ви за имейл.','When verification is temporarily unavailable, the portal retries automatically without signing you out or showing demo data. Sign out ends this browser session. If access expires or is revoked, you must sign in again; this does not change your email preference.')}</p></article>
    </div>
    <section className="card profile-help-roadmap"><strong>{t('Какво следва в документацията','Documentation roadmap')}</strong><p>{t('За всяко меню ще добавим предназначение, източник на данните, нужни права, значение на настройките и състоянията при липса на данни или връзка. Неподготвените раздели няма да се представят като готово ръководство.','Each menu section will get its purpose, data source, required permissions, setting definitions, and empty/offline states. Unwritten sections will not be presented as completed guidance.')}</p></section>
  </div>;
}
