"use client";

import { useState } from "react";
import { scheduleValues } from "./data";
import { Check, PanelTitle } from "./shared";
import type { UiLanguage } from "../i18n/messages";

export function Schedule({notify,lang}:{notify:(v:string)=>void;lang:UiLanguage}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const [editable,setEditable] = useState(scheduleValues);
  const change = (i:number) => setEditable(v=>v.map((x,n)=>n===i?(x>=50?-50:x+10):x));
  return <><div className="schedule-toolbar card"><div><span>{t("Прогнозен резултат","Forecast result")}</span><strong>+1097.39 €</strong><small>{t("+16.5% спрямо пасивен режим","+16.5% versus passive mode")}</small></div><div><span>{t("Очакван SOC в 24:00","Expected SOC at 24:00")}</span><strong>54%</strong><small>{t("Над минималния резерв","Above minimum reserve")}</small></div><div><span>{t("Статус към оператор","Operator status")}</span><strong className="positive">{t("Приет","Accepted")}</strong><small>{t("Изпратен в 13:42","Sent at 13:42")}</small></div><button className="primary-btn" onClick={()=>notify(t("Графикът е записан и изпратен","Schedule saved and sent"))}>{t("Запази и изпрати","Save & send")}</button></div><article className="card schedule-card"><PanelTitle eyebrow={t("15-МИНУТЕН ГРАФИК / АГРЕГИРАН ПО ЧАС","15-MINUTE SCHEDULE / HOURLY AGGREGATE")} title={t("Заряд и разряд","Charge & discharge")} action={<div className="legend"><span className="green-key">{t("Разряд","Discharge")}</span><span className="blue-key">{t("Заряд","Charge")}</span></div>}/><div className="schedule-chart">{editable.map((v,i)=><button key={i} className={v>=0?"discharge":"charging"} onClick={()=>change(i)} title={`${String(i).padStart(2,"0")}:00 · ${v} kW`}><span style={{height:`${Math.abs(v)*1.8}px`}}/><em>{i%3===0?String(i).padStart(2,"0"):""}</em></button>)}<i className="zero-line"/></div><p className="chart-help">{t("Натиснете колона, за да промените мощността. Над линията е разряд, под нея — заряд.","Select a bar to change power. Above the line is discharge; below it is charge.")}</p></article><section className="lower-grid"><article className="card settings-panel"><PanelTitle eyebrow={t("ПРОГНОЗА","FORECAST")} title={t("Енергия в края на деня","End-of-day energy")}/><div className="forecast-row"><span>{t("PV производство","PV production")}</span><b>4.18 MWh</b></div><div className="forecast-row"><span>{t("Консумация","Consumption")}</span><b>2.76 MWh</b></div><div className="forecast-row"><span>{t("Към мрежата","To grid")}</span><b>1.64 MWh</b></div><div className="forecast-row"><span>{t("Загуби","Losses")}</span><b>0.08 MWh</b></div></article><article className="card settings-panel"><PanelTitle eyebrow={t("ОГРАНИЧЕНИЯ","CONSTRAINTS")} title={t("Проверка на графика","Schedule validation")}/><Check text={t("BMS лимити","BMS limits")}/><Check text={t("Мрежов лимит 780 kW","Grid limit 780 kW")}/><Check text={t("Минимален SOC 20%","Minimum SOC 20%")}/><Check text={t("Налична мощност","Available power")}/></article></section></>;
}
