"use client";

import { useState } from "react";
import type React from "react";
import type { UiLanguage } from "../i18n/messages";
import type { BatteryCostSettings } from "./types";
import { PanelTitle } from "./shared";

type Tab="site"|"pv"|"battery"|"grid"|"market"|"forecast"|"strategy"|"loads"|"edge"|"access";
type Mark="required"|"conditional"|"readonly"|"optional";
type Spec={label:[string,string];value:string;mark?:Mark;kind?:"select"|"number"|"date"|"time";options?:string[];hint?:[string,string]};

function Field({label,mark="optional",value,kind="text",options,hint}:{label:string;mark?:Mark;value:string;kind?:string;options?:string[];hint?:string}){
  return <label className="configuration-field"><span>{label}{mark==="required"&&<b> *</b>}{mark==="conditional"&&<b> ◆</b>}{mark==="readonly"&&<em> 🔒</em>}</span>{kind==="select"?<select defaultValue={value}>{(options??[value]).map(x=><option key={x}>{x}</option>)}</select>:<input type={kind} defaultValue={value} readOnly={mark==="readonly"}/>} {hint&&<small>{hint}</small>}</label>;
}

function Group({eyebrow,title,fields,lang,children}:{eyebrow:string;title:string;fields:Spec[];lang:UiLanguage;children?:React.ReactNode}){
  const tx=([bg,en]:[string,string])=>lang==="en"?en:bg;
  return <article className="card configuration-group"><PanelTitle eyebrow={eyebrow} title={title}/><div className="configuration-grid">{fields.map((f,i)=><Field key={`${f.value}-${i}`} label={tx(f.label)} value={f.value} mark={f.mark} kind={f.kind} options={f.options} hint={f.hint?tx(f.hint):undefined}/>)}{children}</div></article>;
}

export function SettingsHub({notify,lang,batteryCost,setBatteryCost}:{notify:(v:string)=>void;lang:UiLanguage;batteryCost:BatteryCostSettings;setBatteryCost:React.Dispatch<React.SetStateAction<BatteryCostSettings>>}){
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const [tab,setTab]=useState<Tab>("site");
  const [validation,setValidation]=useState<"idle"|"valid">("idle");
  const [changed,setChanged]=useState(false);
  const tabs:Array<[Tab,string]>=[["site",t("Обект","Site")],["pv","PV"],["battery",t("Батерия и PCS","Battery & PCS")],["grid",t("Измерване и мрежа","Metering & grid")],["market",t("Пазар и тарифи","Market & tariffs")],["forecast",t("Прогнози","Forecasts")],["strategy",t("Стратегия","Strategy")],["loads",t("Товари и EV","Loads & EV")],["edge",t("Edge и устройства","Edge & devices")],["access",t("Известия и достъп","Notifications & access")]];
  const groups:Record<Tab,Array<{eye:[string,string];title:[string,string];fields:Spec[]}>>={
    site:[{eye:["ИДЕНТИЧНОСТ И МЕСТОПОЛОЖЕНИЕ","IDENTITY & LOCATION"],title:["Основни данни за обекта","Site master data"],fields:[
      {label:["Организация","Organisation"],value:"GrideX Demo",mark:"required",kind:"select"},{label:["Име на обекта","Site name"],value:"Solar Park East",mark:"required"},{label:["Код на обекта","Site code"],value:"SITE-001",mark:"required"},{label:["Държава","Country"],value:"Bulgaria",mark:"required",kind:"select"},{label:["Географска ширина","Latitude"],value:"42.6977",mark:"required",kind:"number"},{label:["Географска дължина","Longitude"],value:"23.3219",mark:"required",kind:"number"},{label:["Часова зона","Time zone"],value:"Europe/Sofia",mark:"required",kind:"select"},{label:["OpenRemote Site Asset","OpenRemote Site Asset"],value:"or-site-solar-east",mark:"readonly"}
    ]},{eye:["ДОГОВОР И ПАЗАР","CONTRACT & MARKET"],title:["Оперативна принадлежност","Operational ownership"],fields:[{label:["Пазар","Market"],value:"IBEX",mark:"required",kind:"select"},{label:["Търговец/координатор","Trader/coordinator"],value:"Demo Energy Trader",mark:"conditional"},{label:["Код за покупка","Import schedule code"],value:"GX-IMP-0142",mark:"conditional"},{label:["Код за продажба","Export schedule code"],value:"GX-EXP-0142",mark:"conditional"},{label:["Пазарен интервал","Settlement interval"],value:"15 min",mark:"required",kind:"select",options:["15 min","60 min"]},{label:["Статус","Status"],value:t("Въвеждане в експлоатация","Commissioning"),mark:"readonly"}]}],
    pv:[{eye:["PV МАСИВ 01","PV ARRAY 01"],title:["Физическа конфигурация за прогнозиране","Physical forecast configuration"],fields:[{label:["Име на масива","Array name"],value:t("Южен покрив","South roof"),mark:"required"},{label:["Ориентационен профил","Orientation profile"],value:"South",mark:"required",kind:"select",options:["South","East-West","East","West","Mixed","Custom"]},{label:["Монтаж","Mounting type"],value:"Rooftop",mark:"required",kind:"select",options:["Rooftop","Ground","Carport","Facade","Floating"]},{label:["Проследяване","Tracking type"],value:"Fixed",mark:"required",kind:"select",options:["Fixed","Single-axis","Dual-axis"]},{label:["Разположение на модулите","Module layout"],value:"2P",mark:"conditional",kind:"select",options:["1P","2P"]},{label:["DC мощност (kWp)","DC capacity (kWp)"],value:"125.000",mark:"required",kind:"number"},{label:["Наклон (°)","Tilt (°)"],value:"25",mark:"required",kind:"number"},{label:["Азимут (°; 180 = юг)","Azimuth (°; 180 = south)"],value:"180",mark:"required",kind:"number"},{label:["Дял изток/запад (%)","East/west split (%)"],value:"50/50",mark:"conditional"},{label:["Коефициент PR","Performance ratio (PR)"],value:"0.82",mark:"required",kind:"number"},{label:["Температурен коефициент (%/°C)","Temperature coefficient (%/°C)"],value:"-0.35",kind:"number"},{label:["Загуби от засенчване (%)","Shading loss (%)"],value:"2.5",kind:"number"},{label:["Инвертор","Inverter"],value:"INV-01 · Huawei SUN2000",mark:"required",kind:"select"},{label:["OpenRemote SolarPVAsset","OpenRemote SolarPVAsset"],value:"or-pv-array-01",mark:"readonly"}]},{eye:["ПРАВИЛА ЗА МОДЕЛИРАНЕ","MODELLING RULES"],title:["Масиви и прогнозен хоризонт","Arrays and forecast horizon"],fields:[{label:["Координати","Coordinates"],value:t("Наследени от SITE-001","Inherited from SITE-001"),mark:"readonly"},{label:["Хоризонт","Horizon"],value:"72 h",mark:"required",kind:"select",options:["24 h","48 h","72 h"]},{label:["Обща DC мощност","Total DC capacity"],value:"250.000 kWp",mark:"readonly"},{label:["Синхронизация","Synchronisation"],value:t("Чернова · не е изпратена","Draft · not sent"),mark:"readonly"}]}],
    battery:[{eye:["БАТЕРИЙНА СИСТЕМА","BATTERY SYSTEM"],title:["Технически и икономически параметри","Technical and economic parameters"],fields:[{label:["Тип система","System type"],value:"All-in-one",mark:"required",kind:"select",options:["Battery only","PCS only","All-in-one"]},{label:["Свързване","Coupling"],value:"AC-coupled",mark:"required",kind:"select",options:["AC-coupled","DC-coupled"]},{label:["Производител и модел","Manufacturer and model"],value:"Suntech SunPro 261",mark:"required",kind:"select"},{label:["Използваем капацитет (kWh)","Usable capacity (kWh)"],value:"261",mark:"required",kind:"number"},{label:["Номинална PCS мощност (kW)","Rated PCS power (kW)"],value:"125",mark:"required",kind:"number"},{label:["Минимален / максимален SOC (%)","Minimum / maximum SOC (%)"],value:"10 / 95",mark:"required"},{label:["Ефективност заряд/разряд (%)","Charge/discharge efficiency (%)"],value:"94 / 94",mark:"required"},{label:["Гарантирани цикли","Warranted cycles"],value:"6000",mark:"required",kind:"number"},{label:["Стойност на актива (€)","Asset value (€)"],value:"118000",mark:"required",kind:"number"},{label:["Остатъчна стойност (€)","Residual value (€)"],value:"11800",kind:"number"},{label:["Полезен живот (месеци)","Useful life (months)"],value:"120",mark:"required",kind:"number"},{label:["Разход за деградация (€/EFC)","Degradation cost (€/EFC)"],value:"17.70",mark:"readonly"}]},{eye:["БЕЗОПАСЕН РАБОТЕН ДИАПАЗОН","SAFE OPERATING ENVELOPE"],title:["BMS ограничения и разрешения","BMS limits and permissions"],fields:[{label:["BMS лимит заряд (kW)","BMS charge limit (kW)"],value:"125",mark:"readonly"},{label:["BMS лимит разряд (kW)","BMS discharge limit (kW)"],value:"125",mark:"readonly"},{label:["Зареждане от мрежата","Grid charging"],value:"Allowed",mark:"required",kind:"select",options:["Allowed","Prohibited"]},{label:["Износ от батерията","Battery export"],value:"Allowed",mark:"required",kind:"select",options:["Allowed","Prohibited"]},{label:["Резервен SOC (%)","Reserve SOC (%)"],value:"20",mark:"required",kind:"number"},{label:["Сигнал за живот (heartbeat)","Heartbeat interval"],value:"60 s · refresh < 50 s",mark:"readonly"}]}],
    grid:[{eye:["ТОЧКИ НА ИЗМЕРВАНЕ","MEASUREMENT POINTS"],title:["Електромери и посока на енергията","Meters and energy direction"],fields:[{label:["Главен PCC електромер","Primary PCC meter"],value:"MTR-01 · Janitza UMG",mark:"required",kind:"select"},{label:["Посока на знака","Sign convention"],value:"Import positive",mark:"required",kind:"select",options:["Import positive","Export positive"]},{label:["PV електромер","PV meter"],value:"MTR-02",mark:"conditional",kind:"select"},{label:["BESS електромер","BESS meter"],value:"MTR-03",mark:"conditional",kind:"select"},{label:["CT/VT коефициент","CT/VT ratio"],value:"1000/5 · 1/1",mark:"required"},{label:["Фазов ред","Phase sequence"],value:"L1-L2-L3",mark:"required",kind:"select"}]},{eye:["МРЕЖОВИ ОГРАНИЧЕНИЯ","GRID CONSTRAINTS"],title:["Договорни лимити и софтуерен предпазител","Contract limits and software fuse"],fields:[{label:["Максимален внос (kW)","Maximum import (kW)"],value:"780",mark:"required",kind:"number"},{label:["Максимален износ (kW)","Maximum export (kW)"],value:"450",mark:"required",kind:"number"},{label:["Предпазен резерв (kW)","Safety margin (kW)"],value:"30",mark:"required",kind:"number"},{label:["Zero-export толеранс (kW)","Zero-export tolerance (kW)"],value:"2",mark:"conditional",kind:"number"},{label:["При липса на измерване","When meter is unavailable"],value:"Safe idle",mark:"required",kind:"select",options:["Safe idle","Fixed fallback limit"]},{label:["Свободен капацитет","Available capacity"],value:"656 kW",mark:"readonly"}]}],
    market:[{eye:["ЦЕНОВИ КОМПОНЕНТИ","PRICE COMPONENTS"],title:["Пълна покупна и продажна цена","All-in import and export price"],fields:[{label:["Валута","Currency"],value:"EUR",mark:"required",kind:"select"},{label:["Източник ден-напред","Day-ahead source"],value:"IBEX",mark:"required",kind:"select",options:["IBEX","ENTSO-E"]},{label:["Мрежови такси внос (€/MWh)","Import network fees (€/MWh)"],value:"42.80",mark:"required",kind:"number"},{label:["Мрежови такси износ (€/MWh)","Export network fees (€/MWh)"],value:"4.20",mark:"required",kind:"number"},{label:["Търговска комисиона (€/MWh)","Trader commission (€/MWh)"],value:"3.50",mark:"required",kind:"number"},{label:["Риск небаланс (€/MWh)","Imbalance risk (€/MWh)"],value:"12.00",mark:"required",kind:"number"},{label:["Валидно от","Valid from"],value:"2026-01-01",mark:"required",kind:"date"}]},{eye:["ГРАФИК КЪМ ТЪРГОВЕЦ","TRADER SCHEDULE"],title:["96 интервала по 15 минути","96 fifteen-minute intervals"],fields:[{label:["Краен час","Submission deadline"],value:"11:30",mark:"required",kind:"time"},{label:["Формат","Format"],value:"CSV",mark:"required",kind:"select",options:["CSV","JSON","XML"]},{label:["Канал","Channel"],value:"SFTP/API",mark:"required",kind:"select",options:["SFTP/API","Email"]},{label:["Получател","Recipient"],value:"schedule@example.invalid",mark:"required"},{label:["Последно приет","Last accepted"],value:"v18 · 13:42",mark:"readonly"}]}],
    forecast:[{eye:["МОДЕЛИ И ИЗТОЧНИЦИ","MODELS & SOURCES"],title:["Прогнози за 72 часа","72-hour forecasts"],fields:[{label:["Ценови модел 1","Price model 1"],value:"GrideX research model",mark:"required",kind:"select",options:["GrideX research model","XGBoost","Persistence baseline"]},{label:["Ценови модел 2","Price model 2"],value:"XGBoost",mark:"required",kind:"select",options:["XGBoost","GrideX research model"]},{label:["Метео доставчик","Weather provider"],value:"Open-Meteo",mark:"required",kind:"select"},{label:["PV модел","PV model"],value:"Physical irradiance + calibration",mark:"required",kind:"select"},{label:["Load модел","Load model"],value:"Gradient boosting",mark:"required",kind:"select"},{label:["ERP вход","ERP expected-load input"],value:"Enabled",mark:"conditional",kind:"select",options:["Enabled","Disabled"]},{label:["Хоризонт","Horizon"],value:"72 h",mark:"required",kind:"select",options:["24 h","48 h","72 h"]},{label:["Интервал","Resolution"],value:"15 min",mark:"required",kind:"select"}]},{eye:["КАЧЕСТВО И РЕЗЕРВИ","QUALITY & FALLBACKS"],title:["Кога прогнозата може да управлява","When forecasts may control"],fields:[{label:["Минимална увереност (%)","Minimum confidence (%)"],value:"75",mark:"required",kind:"number"},{label:["Максимална възраст (min)","Maximum age (min)"],value:"30",mark:"required",kind:"number"},{label:["Период за обучение (дни)","Training window (days)"],value:"365",mark:"required",kind:"number"},{label:["Резервен модел","Fallback model"],value:"Persistence baseline",mark:"required",kind:"select"},{label:["Изгрев / залез","Sunrise / sunset"],value:"06:34 / 20:18",mark:"readonly"},{label:["Последна прогноза","Last forecast"],value:"14:30 · GOOD",mark:"readonly"}]}],
    strategy:[{eye:["ОПТИМИЗАЦИОННА ПОЛИТИКА","OPTIMISATION POLICY"],title:["Икономика и безопасност","Economics and safety"],fields:[{label:["Стратегия","Strategy"],value:"Intelligent hybrid",mark:"required",kind:"select",options:["Intelligent hybrid","Price arbitrage","Own consumption","Zero export","Peak shaving","Schedule following"]},{label:["Резервен режим","Fallback mode"],value:"Safe idle",mark:"required",kind:"select"},{label:["Интервал за управление (s)","Control interval (s)"],value:"60",mark:"required",kind:"number"},{label:["Преоптимизация (min)","Re-optimisation (min)"],value:"15",mark:"required",kind:"number"},{label:["Минимална печалба (€/ден)","Minimum profit (€/day)"],value:"25",mark:"required",kind:"number"},{label:["Минимален спред (€/MWh)","Minimum spread (€/MWh)"],value:"38",mark:"required",kind:"number"},{label:["Не продавай на загуба","Do not export at a loss"],value:"Full cost",mark:"required",kind:"select",options:["Cash cost","Full cost","Disabled"]},{label:["PV праг (€/MWh)","PV export floor (€/MWh)"],value:"19.20",mark:"required",kind:"number"},{label:["BESS праг (€/MWh)","BESS export floor (€/MWh)"],value:"105.70",mark:"required",kind:"number"},{label:["SOC при ниско слънце (%)","Low-solar reserve SOC (%)"],value:"80",mark:"conditional",kind:"number"},{label:["Произход на заряда","Charge-origin tracking"],value:"Grid + PV",mark:"required",kind:"select"},{label:["Активна версия","Active revision"],value:"v5 · applied",mark:"readonly"}]},{eye:["СИМУЛАЦИЯ","SIMULATION"],title:["Очакван резултат преди активиране","Projected result before activation"],fields:[{label:["Нетна печалба / 24 h","Net profit / 24 h"],value:"€1,032.00",mark:"readonly"},{label:["Прогнозни EFC / 24 h","Projected EFC / 24 h"],value:"0.82 (grid 0.46 · PV 0.31)",mark:"readonly"},{label:["BMS лимити","BMS limits"],value:"Valid",mark:"readonly"},{label:["Прогнози","Forecasts"],value:"2 price + weather + PV + load",mark:"readonly"}]}],
    loads:[{eye:["УПРАВЛЯЕМИ ТОВАРИ","FLEXIBLE LOADS"],title:["Приоритети, ограничения и ERP","Priorities, constraints and ERP"],fields:[{label:["Товар","Load"],value:"Heat pump 01",mark:"required",kind:"select"},{label:["Приоритет","Priority"],value:"2",mark:"required",kind:"number"},{label:["Мин./макс. мощност (kW)","Min./max. power (kW)"],value:"20 / 120",mark:"required"},{label:["Енергийна цел (kWh)","Energy target (kWh)"],value:"480",mark:"conditional",kind:"number"},{label:["Краен час","Deadline"],value:"18:00",mark:"conditional",kind:"time"},{label:["ERP сигнал","ERP signal"],value:"Production plan API",mark:"conditional",kind:"select"},{label:["При прекъсване","Interruption policy"],value:"Resume automatically",mark:"required",kind:"select"}]},{eye:["EVSE","EVSE"],title:["Зарядни станции и динамична тарифа","Chargers and dynamic tariff"],fields:[{label:["Зарядна станция","Charger"],value:"EVSE-01 · OCPP",mark:"required",kind:"select"},{label:["Макс. мощност (kW)","Maximum power (kW)"],value:"132",mark:"required",kind:"number"},{label:["Минимална цена (€/MWh)","Minimum price (€/MWh)"],value:"420",mark:"required",kind:"number"},{label:["Надбавка (€/MWh)","Markup (€/MWh)"],value:"180",mark:"required",kind:"number"},{label:["Приоритет PV излишък","PV surplus priority"],value:"Battery, then EV",mark:"required",kind:"select"},{label:["OCPP статус","OCPP status"],value:"Available",mark:"readonly"}]}],
    edge:[{eye:["ТОПОЛОГИЯ НА ОБЕКТА","SITE TOPOLOGY"],title:["Управляващ модул и гейтове","Controller and gateways"],fields:[{label:["Управляващ модул","Controller"],value:"ROCK Pi E · RK3328",mark:"required",kind:"select"},{label:["Вътрешен Ethernet","Internal Ethernet"],value:"OT / Modbus TCP",mark:"required",kind:"select"},{label:["Външен Ethernet","Uplink Ethernet"],value:"Site Router / backend",mark:"required",kind:"select"},{label:["Нод","Node"],value:"OLIMEX ESP32-EVB-EA-IND",mark:"required",kind:"select"},{label:["Интерфейс","Device interface"],value:"CAN",mark:"required",kind:"select",options:["CAN","RS-485","RS-232","Ethernet"]},{label:["Тип устройство","Device type"],value:"Battery",mark:"required",kind:"select",options:["Battery","Inverter","Meter","EVSE"]},{label:["Драйвер","Driver"],value:"suntech-sunpro-261-v2",mark:"required",kind:"select"},{label:["Правило за гейт","Gateway rule"],value:t("1 тип · 1 брой · 1 бранд","1 type · 1 unit · 1 brand"),mark:"readonly"}]},{eye:["СИНХРОНИЗАЦИЯ","SYNCHRONISATION"],title:["Backend, MQTT и OpenRemote","Backend, MQTT and OpenRemote"],fields:[{label:["Телеметрия","Telemetry"],value:"ESP32 → MQTT via Site Router VPN",mark:"readonly"},{label:["Команди","Commands"],value:"OpenRemote → GrideX API → ROCK Pi",mark:"readonly"},{label:["Последен heartbeat","Last heartbeat"],value:"8 s ago · GOOD",mark:"readonly"},{label:["Версия драйвер","Driver version"],value:"2.0.0",mark:"readonly"},{label:["Конфигурационен пакет","Configuration package"],value:"cfg-v5 · signed",mark:"readonly"}]}],
    access:[{eye:["ИЗВЕСТИЯ","NOTIFICATIONS"],title:["Канали и ескалация","Channels and escalation"],fields:[{label:["Основен получател","Primary recipient"],value:"energy.manager@example.invalid",mark:"required"},{label:["Минимална тежест","Minimum severity"],value:"Warning",mark:"required",kind:"select",options:["Info","Warning","Critical"]},{label:["Канали","Channels"],value:"Push + Email",mark:"required",kind:"select"},{label:["Повторение","Repeat interval"],value:"30 min",mark:"required",kind:"select"},{label:["Тихи часове","Quiet hours"],value:"22:00–07:00"},{label:["Месечен отчет","Monthly report"],value:"Day 1 · 08:00"}]},{eye:["ДОСТЪП И ОДИТ","ACCESS & AUDIT"],title:["Роли и защитени действия","Roles and protected actions"],fields:[{label:["Роля за редакция","Edit role"],value:"Site administrator",mark:"required",kind:"select"},{label:["Роля за активиране","Activation role"],value:"EMS operator",mark:"required",kind:"select"},{label:["Двойно одобрение","Dual approval"],value:"Required",mark:"required",kind:"select"},{label:["Identity provider","Identity provider"],value:"Keycloak · gridex realm",mark:"readonly"},{label:["Последна промяна","Last change"],value:"admin@example.invalid · v5",mark:"readonly"},{label:["Одит","Audit"],value:"Immutable · 7 years",mark:"readonly"}]}]
  };
  return <div className="settings-hub" data-no-translate onChange={()=>{setChanged(true);setValidation("idle")}}>
    <section className="settings-overview card"><div><p>{t("ЦЕНТЪР ЗА КОНФИГУРАЦИЯ","CONFIGURATION CENTRE")}</p><h2>{t("Една валидирана конфигурация за целия обект","One validated configuration for the entire site")}</h2><span>{t("PostgreSQL пази версиите и правата. OpenRemote получава само активните оперативни параметри; BMS и Edge защитите остават с най-висок приоритет.","PostgreSQL owns versions and permissions. OpenRemote receives only active operational parameters; BMS and Edge safety always have priority.")}</span></div><span className="settings-health"><i>{validation==="valid"?"✓":"6"}</i><b>{validation==="valid"?t("Валидна","Valid"):t("Чернова v6","Draft v6")}</b><small>{changed?t("незаписани промени","unsaved changes"):t("OpenRemote чака активиране","OpenRemote awaits activation")}</small></span></section>
    <div className="configuration-legend card"><span><b>*</b> {t("Задължително","Required")}</span><span><b>◆</b> {t("Условно задължително","Conditionally required")}</span><span>🔒 {t("Само за четене","Read-only")}</span></div>
    <div className="subnav settings-tabs configuration-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</div>
    <section className="configuration-layout">{groups[tab].map((g,i)=><Group key={i} eyebrow={t(...g.eye)} title={t(...g.title)} fields={g.fields} lang={lang}>{tab==="battery"&&i===1&&<div className="switch-row configuration-wide"><span><strong>{t("Включи амортизацията в решенията","Include depreciation in decisions")}</strong><small>{t("Ежедневно начисляване спрямо EFC и стратегията","Daily accrual by EFC and strategy")}</small></span><button type="button" className={batteryCost.included?"toggle on":"toggle"} onClick={()=>setBatteryCost(v=>({...v,included:!v.included}))}/></div>}{tab==="pv"&&i===1&&<div className="configuration-callout">{t("Изток–запад се моделира като два масива с реални азимути. „2P tracker“ е комбинация от полетата проследяване и разположение.","East–west is modelled as two arrays with real azimuths. A “2P tracker” combines tracking type and module layout.")}</div>}{tab==="edge"&&i===1&&<div className="configuration-callout">{t("WireGuard завършва на Site Router. ROCK Pi и ESP32 нямат VPN ключове.","WireGuard terminates on the Site Router. ROCK Pi and ESP32 hold no VPN keys.")}</div>}</Group>)}</section>
    <section className="configuration-actions card"><div><strong>{t("Версия v6 · Чернова","Version v6 · Draft")}</strong><span>{t("Записването не променя OpenRemote. Активирането изисква успешна валидация и симулация.","Saving does not change OpenRemote. Activation requires successful validation and simulation.")}</span></div><button onClick={()=>notify(t("JSON е подготвен за експорт","JSON export prepared"))}>{t("Експорт JSON","Export JSON")}</button><button onClick={()=>{setChanged(false);notify(t("Черновата е записана","Draft saved"))}}>{t("Запази чернова","Save draft")}</button><button onClick={()=>{setValidation("valid");notify(t("Конфигурацията е валидна","Configuration is valid"))}}>{t("Валидирай","Validate")}</button><button className="primary-btn" disabled={validation!=="valid"} onClick={()=>notify(t("Изпратено за симулация и активиране","Sent for simulation and activation"))}>{t("Симулирай и активирай","Simulate & activate")}</button></section>
  </div>;
}
