"use client";

import { useState } from "react";
import type React from "react";
import type { UiLanguage } from "../i18n/messages";
import type { BatteryCostSettings } from "./types";
import { Check, ModeRange, PanelTitle } from "./shared";

export function SettingsHub({notify,lang,batteryCost,setBatteryCost}:{notify:(v:string)=>void;lang:UiLanguage;batteryCost:BatteryCostSettings;setBatteryCost:React.Dispatch<React.SetStateAction<BatteryCostSettings>>}) {
  const t=(bg:string,en:string)=>lang==="en"?en:bg;
  const [tab,setTab]=useState<"site"|"pv"|"bess"|"ev"|"notify">("site");
  const [weatherWeight,setWeatherWeight]=useState(72);
  const [bias,setBias]=useState(-8);
  const [learningDays,setLearningDays]=useState(45);
  const [lossDays,setLossDays]=useState(30);
  const [negativeStop,setNegativeStop]=useState(true);
  const [gridCharge,setGridCharge]=useState(true);
  const [gridDischarge,setGridDischarge]=useState(true);
  const [exportLimit,setExportLimit]=useState(450);
  const [evMargin,setEvMargin]=useState(180);
  const [evMin,setEvMin]=useState(420);
  const [evHorizon,setEvHorizon]=useState(3);
  const [notifyEmail,setNotifyEmail]=useState("energy.manager@client.bg");
  const tabs:[[typeof tab,string],...Array<[typeof tab,string]>]=[["site",t("Обект и пазар","Site & market")],["pv",t("PV и прогноза","PV & forecast")],["bess","BESS"],["ev",t("EV тарифи","EV tariffs")],["notify",t("Известия","Notifications")]];
  return <div className="settings-hub" data-no-translate><section className="settings-overview card"><div><p>{t("ЕДНА КОНФИГУРАЦИЯ ЗА ЦЯЛАТА EMS","ONE CONFIGURATION FOR THE ENTIRE EMS")}</p><h2>{t("Договорни, прогнозни и технически ограничения","Contractual, forecast and technical constraints")}</h2><span>{t("Пазарната стратегия използва само валидирани настройки. Safety границите от BMS и Edge никога не могат да бъдат заобиколени.","The market strategy uses validated settings only. BMS and Edge safety boundaries can never be bypassed.")}</span></div><span className="settings-health"><i>✓</i><b>42 / 42</b><small>{t("валидирани полета","validated fields")}</small></span></section><div className="subnav settings-tabs">{tabs.map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</div>
  {tab==="site"&&<section className="settings-two"><article className="card config-card"><PanelTitle eyebrow={t("ОБЕКТ И ИЗМЕРВАНЕ","SITE & METERING")} title="Solar Park East"/><div className="config-form"><label><span>{t("Държава / пазар","Country / market")}</span><select><option>Bulgaria · IBEX</option></select></label><label><span>{t("Часова зона","Time zone")}</span><select><option>Europe/Sofia · UTC+2/+3</option></select></label><label><span>{t("Пазарен интервал","Market interval")}</span><select><option>15 min</option><option>60 min</option></select></label><label><span>{t("Резервна средна консумация","Fallback average load")}</span><div className="input-unit"><input defaultValue="124"/><b>kW</b></div></label><label><span>{t("Продажба по договор","Export agreement")}</span><select><option>{t("Да · валидиран","Yes · validated")}</option></select></label><label><span>{t("Регулиран пазар за покупка","Regulated import market")}</span><select><option>{t("Не","No")}</option><option>{t("Да","Yes")}</option></select></label></div></article><article className="card trader-card"><PanelTitle eyebrow={t("ГРАФИК КЪМ ТЪРГОВЕЦ","TRADER SCHEDULE")} title={t("Автоматична доставка до 11:30","Automatic delivery by 11:30")}/><div><span><small>{t("Получател","Recipient")}</small><strong>schedule@energy-trader.bg</strong></span><span><small>{t("Код покупка","Import code")}</small><strong>BG-GX-IMP-0142</strong></span><span><small>{t("Код продажба","Export code")}</small><strong>BG-GX-EXP-0142</strong></span><span><small>{t("Формат","Format")}</small><strong>CSV · 96 × 15 min</strong></span></div><Check text={t("Последният график е приет","Latest schedule accepted")}/><button className="primary-btn" onClick={()=>notify(t("Тестовият график е изпратен","Test schedule sent"))}>{t("Изпрати тест","Send test")}</button></article></section>}
  {tab==="pv"&&<section className="settings-two"><article className="card config-card"><PanelTitle eyebrow={t("КАЛИБРАЦИЯ НА ПРОГНОЗАТА","FORECAST CALIBRATION")} title={t("Време срещу реално производство","Weather versus actual generation")}/><ModeRange label={t("Тежест на прогнозата за времето","Weather forecast weight")} value={weatherWeight} unit="%" min={0} max={100} onChange={setWeatherWeight}/><ModeRange label={t("Консервативна корекция","Conservative bias")} value={bias} unit="%" min={-30} max={20} onChange={setBias}/><ModeRange label={t("Период за самообучение","Self-learning period")} value={learningDays} unit={t("дни","days")} min={7} max={180} onChange={setLearningDays}/><div className="forecast-calibration"><span><small>{t("Прогноза утре","Tomorrow forecast")}</small><strong>3.42 MWh</strong></span><b>→</b><span><small>{t("След корекция","After calibration")}</small><strong>{(3.42*(1+bias/100)).toFixed(2)} MWh</strong></span></div></article><article className="card config-card"><PanelTitle eyebrow={t("ОТРИЦАТЕЛНИ ЦЕНИ И ОГРАНИЧАВАНЕ","NEGATIVE PRICE & CURTAILMENT")} title={t("Не продавай на загуба","Do not export at a loss")}/><div className="switch-row"><span><strong>{t("Автоматично спиране на продажбата","Automatic export stop")}</strong><small>{t("Пълна цена след такси и комисионни","All-in price after fees and commissions")}</small></span><button className={negativeStop?"toggle on":"toggle"} onClick={()=>setNegativeStop(v=>!v)}/></div><div className="setting-row"><span>{t("Праг за спиране","Stop threshold")}</span><b>−18 EUR/MWh</b></div><div className="setting-row"><span>{t("Ръчен график за ограничаване","Manual curtailment schedule")}</span><b>{t("Разрешен","Enabled")}</b></div><div className="setting-row"><span>{t("Известяване","Notification")}</span><b>Push + Email</b></div><button className="primary-btn" onClick={()=>notify(t("PV настройките са записани","PV settings saved"))}>{t("Запази PV политиката","Save PV policy")}</button></article></section>}
  {tab==="bess"&&<section className="settings-two"><article className="card config-card"><PanelTitle eyebrow={t("РАЗРЕШЕНИЯ И ДОГОВОРНИ ЛИМИТИ","PERMISSIONS & CONTRACT LIMITS")} title={t("Мрежа, PV и батерия","Grid, PV and battery")}/><div className="switch-row"><span><strong>{t("Зареждане от мрежата","Grid charging")}</strong><small>{t("Разрешено по договор","Permitted by contract")}</small></span><button className={gridCharge?"toggle on":"toggle"} onClick={()=>setGridCharge(v=>!v)}/></div><div className="switch-row"><span><strong>{t("Разреждане към мрежата","Grid export")}</strong><small>{t("Разрешено по договор","Permitted by contract")}</small></span><button className={gridDischarge?"toggle on":"toggle"} onClick={()=>setGridDischarge(v=>!v)}/></div><ModeRange label={t("Максимално отдаване по договор","Contract export limit")} value={exportLimit} unit="kW" min={0} max={780} onChange={setExportLimit}/><div className="setting-row"><span>{t("Минимална скорост на разреждане","Minimum discharge power")}</span><b>32 kW</b></div><div className="setting-row"><span>{t("PV + BESS общ export guard","Combined PV + BESS export guard")}</span><b>90%</b></div></article><article className="card config-card"><PanelTitle eyebrow={t("САМООБУЧЕНИЕ НА ЗАГУБИТЕ","LOSS SELF-LEARNING")} title={t("Отделни модели по режим и мощност","Separate models by mode and power")}/><ModeRange label={t("Исторически период","Historical period")} value={lossDays} unit={t("дни","days")} min={7} max={180} onChange={setLossDays}/><div className="loss-models"><span><small>{t("Зареждане","Charging")}</small><strong>8.1%</strong><em>100–450 kW</em></span><span><small>{t("Разреждане","Discharging")}</small><strong>7.4%</strong><em>80–500 kW</em></span><span><small>{t("Самоконсумация","Self-consumption")}</small><strong>11.8%</strong><em>20–140 kW</em></span></div><div className="switch-row"><span><strong>{t("Включи ДМА в решенията","Include depreciation in decisions")}</strong><small>{batteryCost.included?t("Активно","Active"):t("Изключено","Disabled")}</small></span><button className={batteryCost.included?"toggle on":"toggle"} onClick={()=>setBatteryCost(v=>({...v,included:!v.included}))}/></div><button className="primary-btn" onClick={()=>notify(t("BESS политиката е записана","BESS policy saved"))}>{t("Запази BESS политиката","Save BESS policy")}</button></article></section>}
  {tab==="ev"&&<section className="settings-two"><article className="card config-card"><PanelTitle eyebrow={t("ДИНАМИЧНА EV ТАРИФА","DYNAMIC EV TARIFF")} title={t("Пазарна цена + гарантиран марж","Market price + guaranteed margin")}/><ModeRange label={t("Надбавка","Markup")} value={evMargin} unit="EUR/MWh" min={0} max={500} onChange={setEvMargin}/><ModeRange label={t("Минимална клиентска цена","Minimum customer price")} value={evMin} unit="EUR/MWh" min={100} max={900} onChange={setEvMin}/><ModeRange label={t("Хоризонт за максимална цена","Maximum-price horizon")} value={evHorizon} unit="h" min={1} max={8} onChange={setEvHorizon}/><div className="ev-price-result"><span><small>{t("IBEX + тарифи","IBEX + tariffs")}</small><strong>241.60</strong></span><b>+</b><span><small>{t("Надбавка","Markup")}</small><strong>{evMargin}</strong></span><b>=</b><span><small>{t("Клиентска цена","Customer price")}</small><strong>{Math.max(evMin,241.6+evMargin).toFixed(2)} EUR/MWh</strong></span></div></article><article className="card config-card"><PanelTitle eyebrow="EV POWER CONTROL" title={t("Мощност според свободния капацитет","Power from available site capacity")}/><div className="setting-row"><span>{t("Максимална мощност станция","Charger maximum power")}</span><b>132 kW</b></div><div className="setting-row"><span>Software fuse</span><b>180 kW</b></div><div className="setting-row"><span>{t("PV излишък в цената","PV surplus in tariff")}</span><b>{t("Да","Yes")}</b></div><div className="setting-row"><span>{t("Последно обновяване","Last update")}</span><b>14:31:08</b></div><button className="primary-btn" onClick={()=>notify(t("EV тарифата и мощностният лимит са обновени","EV tariff and power limit updated"))}>{t("Публикувай EV тарифа","Publish EV tariff")}</button></article></section>}
  {tab==="notify"&&<section className="settings-two"><article className="card config-card"><PanelTitle eyebrow={t("ПОЛУЧАТЕЛИ И КАНАЛИ","RECIPIENTS & CHANNELS")} title={t("Оперативни известия","Operational notifications")}/><label className="notify-email"><span>{t("Допълнителен получател","Additional recipient")}</span><input value={notifyEmail} onChange={e=>setNotifyEmail(e.target.value)}/></label><div className="notification-channels"><button className="active">Push</button><button className="active">Email</button><button>SMS</button><button>Webhook</button></div><div className="setting-row"><span>{t("Повторение при непотвърдена аларма","Repeat unacknowledged alarm")}</span><b>30 min</b></div><div className="setting-row"><span>{t("Месечен управленски отчет","Monthly management report")}</span><b>{t("1-во число · 08:00","1st day · 08:00")}</b></div></article><article className="card notification-matrix"><PanelTitle eyebrow={t("МАТРИЦА НА СЪБИТИЯТА","EVENT MATRIX")} title={t("Какво наблюдава системата","What the system monitors")}/>{[[t("Загуба на интернет / gateway","Internet / gateway loss"),"Critical"],[t("PV, BESS или EV не изпълнява команда","PV, BESS or EV command not executed"),"Critical"],[t("Температура, SOC или мрежов лимит","Temperature, SOC or grid limit"),"Warning"],[t("Необичайна консумация / забравен товар","Abnormal consumption / forgotten load"),"Warning"],[t("График, прогноза и месечен отчет","Schedule, forecast and monthly report"),"Info"]].map(x=><span key={x[0]}><i className={x[1]==="Critical"?"critical":x[1]==="Warning"?"warning":"info"}/><b>{x[0]}</b><small>{x[1]} · Push + Email</small></span>)}<button className="primary-btn" onClick={()=>notify(t("Настройките за известия са записани","Notification settings saved"))}>{t("Запази известията","Save notifications")}</button></article></section>}
  </div>;
}
