import { useCallback } from "react";

export type UiLanguage = "bg" | "en";

export const messages = {
  bg: {
    "nav.overview":"Преглед", "nav.customers":"Клиенти и договори", "nav.sites":"Обекти", "nav.assets":"Енергийни активи", "nav.battery":"Батерия", "nav.schedule":"Графици", "nav.market":"Пазар", "nav.settlement":"Тарифи и сетълмент", "nav.automation":"Логика и режими", "nav.loads":"Управляеми товари", "nav.balance":"Балансиране", "nav.gateway":"Edge шлюз", "nav.supported":"Поддържани устройства", "nav.devices":"Устройства", "nav.alarms":"Аларми", "nav.reports":"Отчети и икономика", "nav.settings":"Настройки", "nav.plans":"Планове и абонамент", "nav.about":"За нас", "nav.profile":"Потребителски профил", "nav.login":"Вход в портала",
    "title.overview":"Соларен парк Изток", "title.customers":"Клиенти и договори", "title.sites":"Моите обекти", "title.assets":"Енергийни активи", "title.battery":"Батерия и оптимизация", "title.schedule":"Енергиен график", "title.market":"Пазар и прогнози", "title.settlement":"Тарифи и сетълмент", "title.automation":"Логика и режими", "title.loads":"Управляеми товари", "title.balance":"Балансираща група", "title.gateway":"Edge шлюз", "title.supported":"Поддържани устройства", "title.devices":"Устройства и SCADA", "title.alarms":"Аларми и събития", "title.reports":"Отчети и икономика", "title.settings":"Настройки", "title.plans":"Планове и абонамент", "title.about":"За нас", "title.profile":"Потребителски профил", "title.login":"Вход в портала",
    "eyebrow.overview":"ПОРТФОЛИО / СОФИЯ", "eyebrow.customers":"ПОРТФОЛИО / CRM", "eyebrow.sites":"ПОРТФОЛИО / 6 ОБЕКТА", "eyebrow.assets":"СОЛАРЕН ПАРК ИЗТОК / АКТИВИ", "eyebrow.battery":"СОЛАРЕН ПАРК ИЗТОК / BESS", "eyebrow.schedule":"СОЛАРЕН ПАРК ИЗТОК / 21 АВГУСТ", "eyebrow.market":"БЪЛГАРИЯ / IBEX ДЕН НАПРЕД", "eyebrow.settlement":"ПОРТФОЛИО / VEM", "eyebrow.automation":"EMS / АВТОМАТИЗАЦИЯ", "eyebrow.loads":"EMS / УПРАВЛЯЕМИ ТОВАРИ", "eyebrow.balance":"GRIDEX / 21 АВГУСТ", "eyebrow.gateway":"GRIDEX EDGE ШЛЮЗ", "eyebrow.supported":"ПОДДЪРЖАНИ УСТРОЙСТВА", "eyebrow.devices":"СОЛАРЕН ПАРК ИЗТОК / 12 УСТРОЙСТВА", "eyebrow.alarms":"ПОРТФОЛИО / АКТИВНИ", "eyebrow.reports":"СОЛАРЕН ПАРК ИЗТОК / АНАЛИЗ", "eyebrow.settings":"СОЛАРЕН ПАРК ИЗТОК / КОНФИГУРАЦИЯ", "eyebrow.plans":"GRIDEX / ЛИЦЕНЗИ", "eyebrow.about":"GRIDEX / SUNSTORAGE PRO", "eyebrow.profile":"GRIDEX / МОЯТ ПРОФИЛ", "eyebrow.login":"GRIDEX / СИГУРЕН ДОСТЪП",
  },
  en: {
    "nav.overview":"Overview", "nav.customers":"Customers & contracts", "nav.sites":"Sites", "nav.assets":"Energy assets", "nav.battery":"Battery", "nav.schedule":"Schedules", "nav.market":"Market", "nav.settlement":"Tariffs & settlement", "nav.automation":"Logic & modes", "nav.loads":"Flexible loads", "nav.balance":"Balancing", "nav.gateway":"Edge gateway", "nav.supported":"Supported devices", "nav.devices":"Devices", "nav.alarms":"Alarms", "nav.reports":"Reports & economics", "nav.settings":"Settings", "nav.plans":"Plans & subscription", "nav.about":"About us", "nav.profile":"User profile", "nav.login":"Sign in",
    "title.overview":"Solar Park East", "title.customers":"Customers & contracts", "title.sites":"My sites", "title.assets":"Energy assets", "title.battery":"Battery & optimisation", "title.schedule":"Energy schedule", "title.market":"Market & forecasts", "title.settlement":"Tariffs & settlement", "title.automation":"Logic & operating modes", "title.loads":"Flexible loads", "title.balance":"Balancing group", "title.gateway":"Edge gateway", "title.supported":"Supported devices", "title.devices":"Devices & SCADA", "title.alarms":"Alarms & events", "title.reports":"Reports & economics", "title.settings":"Settings", "title.plans":"Plans & subscription", "title.about":"About us", "title.profile":"User profile", "title.login":"Sign in",
    "eyebrow.overview":"PORTFOLIO / SOFIA", "eyebrow.customers":"PORTFOLIO / CRM", "eyebrow.sites":"PORTFOLIO / 6 SITES", "eyebrow.assets":"SOLAR PARK EAST / ASSETS", "eyebrow.battery":"BESS / TESVOLT TPS-E", "eyebrow.schedule":"SOLAR PARK EAST / 21 AUGUST", "eyebrow.market":"BULGARIA / IBEX DAY-AHEAD", "eyebrow.settlement":"PORTFOLIO / VEM", "eyebrow.automation":"EMS / AUTOMATION", "eyebrow.loads":"FLEXIBLE LOAD ORCHESTRATION", "eyebrow.balance":"GRIDEX / 21 AUGUST", "eyebrow.gateway":"GRIDEX EDGE GATEWAY", "eyebrow.supported":"SUPPORTED DEVICES", "eyebrow.devices":"SOLAR PARK EAST / 12 DEVICES", "eyebrow.alarms":"PORTFOLIO / ACTIVE", "eyebrow.reports":"SOLAR PARK EAST / ANALYTICS", "eyebrow.settings":"SOLAR PARK EAST / CONFIGURATION", "eyebrow.plans":"GRIDEX / LICENSING", "eyebrow.about":"GRIDEX / SUNSTORAGE PRO", "eyebrow.profile":"GRIDEX / MY PROFILE", "eyebrow.login":"GRIDEX / SECURE ACCESS",
  },
} as const;

export type MessageKey = keyof typeof messages.bg;

export function useT(language: UiLanguage) {
  return useCallback((key: MessageKey) => messages[language][key], [language]);
}
