import {test,expect} from '@playwright/test';

test('deep link and refresh restore SSO; expiry and restart show Demo until explicit login',async({page,context})=>{
  let signedIn=true,nonce='',forceLogins=0,logins=0,serverRestart=false;
  const jwt=(claims:object)=>[Buffer.from('{}').toString('base64url'),Buffer.from(JSON.stringify(claims)).toString('base64url'),'test'].join('.');
  await context.route('**/gridex-config.js',r=>r.fulfill({contentType:'application/javascript',body:`window.__GRIDEX_CONFIG__={mode:'auto',authEnabled:true,apiBaseUrl:'https://api.example.invalid',oidcIssuer:'https://auth.example.invalid/auth/realms/gridex',realm:'gridex',oidcClientId:'gridex-portal'};`}));
  await context.route('https://auth.example.invalid/**',r=>{
    const url=new URL(r.request().url());
    if(url.pathname.endsWith('/auth')) {
      nonce=url.searchParams.get('nonce')!;
      if(url.searchParams.get('prompt')==='login'){forceLogins++;signedIn=true;}
      if(url.searchParams.get('prompt')!=='none')logins++;
      return r.fulfill({status:302,headers:{location:url.searchParams.get('redirect_uri')+'#'+(signedIn?'code=fixture':'error=login_required')+'&state='+url.searchParams.get('state')}});
    }
    if(url.pathname.endsWith('/logout')) {
      expect(url.searchParams.get('post_logout_redirect_uri')).toBe('http://127.0.0.1:4173/demo/');
      signedIn=false;
      return r.fulfill({status:302,headers:{location:url.searchParams.get('post_logout_redirect_uri')!}});
    }
    const now=Math.floor(Date.now()/1000);
    const claims={sub:'owner',iss:'https://auth.example.invalid/auth/realms/gridex',aud:'gridex-portal',iat:now,exp:now+600,nonce,email:'owner@example.invalid'};
    return r.fulfill({json:{access_token:jwt(claims),id_token:jwt(claims),refresh_token:jwt(claims),expires_in:600,token_type:'Bearer'}});
  });
  await context.route('https://api.example.invalid/**',r=>{
    const path=new URL(r.request().url()).pathname;
    if(path.endsWith('/auth/login-realm'))return r.fulfill({json:{realms:['gridex']}});
    if(serverRestart&&forceLogins<2)return r.fulfill({status:401,json:{error:'reauthentication_required'}});
    if(path.endsWith('/me'))return r.fulfill({json:{subject:'owner',realm:'gridex',roles:['administrator'],permissions:[],memberships:[]}});
    if(path.endsWith('/me/navigation'))return r.fulfill({json:{subject:'owner',realm:'gridex',items:['overview','sites','devices','market','profile','help'].map((id,sortOrder)=>({id,sortOrder,visible:true}))}});
    if(path.endsWith('/devices'))return r.fulfill({json:{items:[]}});
    if(path.endsWith('/me/services'))return r.fulfill({json:{services:[{code:'day_ahead'}]}});
    if(path.endsWith('/sites'))return r.fulfill({json:{sites:[{id:'lab',name:'Lab'}]}});
    if(path.endsWith('/hardware'))return r.fulfill({json:{inventorySource:'openremote',gateways:[{id:'rock',name:'ROCK',hardwareModel:'rock-pi-e',role:'controller',ports:[]}],devices:[]}});
    if(path.endsWith('/device-heartbeats'))return r.fulfill({json:{items:[]}});
    if(path.endsWith('/device-setup'))return r.fulfill({json:{revision:0,configuration:{}}});
    return r.fulfill({status:503,json:{error:'unavailable'}});
  });
  await page.goto('/sites/lab/devices/');
  await expect(page.getByRole('heading',{name:'ROCK',exact:true})).toBeVisible();
  await expect(page).toHaveURL(/\/sites\/lab\/devices\/$/);
  await page.reload();
  await expect(page.getByRole('heading',{name:'ROCK',exact:true})).toBeVisible();
  await expect(page).toHaveURL(/\/sites\/lab\/devices\/$/);
  expect(logins).toBe(0);
  await page.getByTestId('mode-link').click();
  await expect(page).toHaveURL(/\/demo\/$/);
  await expect(page.locator('.app-shell')).toHaveAttribute('data-mode','demo');
  await page.locator('[data-view-id="devices"]').click();
  await expect(page).toHaveURL(/\/demo\/infrastructure\/$/);
  await expect(page.locator('main')).not.toContainText('LIVE ·');
  await page.getByTestId('mode-link').click();
  await expect(page).toHaveURL(/\/sites\/lab\/devices\/$/);
  await expect(page.getByRole('heading',{name:'ROCK',exact:true})).toBeVisible();
  expect(logins).toBe(0);
  await expect(page.locator('[data-view-id="battery"]')).toHaveCount(0);
  await page.locator('[data-view-id="market"]').click();
  await expect(page).toHaveURL(/\/services\/day-ahead\/$/);
  await page.goBack();
  await expect(page.getByRole('heading',{name:'ROCK',exact:true})).toBeVisible();
  await page.evaluate(()=>localStorage.setItem('gridex.session-release','old-release'));
  await page.reload();
  await expect(page).toHaveURL(/\/demo\/$/);
  await expect(page.locator('.app-shell')).toHaveAttribute('data-mode','demo');
  await expect(page.locator('main')).not.toContainText('Private ROCK');
  expect(forceLogins).toBe(0);
  await page.locator('.demo-sign-in').click();
  await page.getByLabel('Имейл',{exact:true}).fill('owner@example.invalid');
  await page.locator('.login-submit').click();
  await expect(page.getByRole('heading',{name:'Входът е успешен'})).toBeVisible();
  await expect(page).toHaveURL(/\/$/);
  await expect(page.getByTestId('section-overview')).toBeVisible();
  await expect(page.locator('.profile small')).toHaveText('Администратор');
  expect(forceLogins).toBe(1);
  serverRestart=true;
  await page.goto('/sites/lab/devices/');
  await expect(page).toHaveURL(/\/demo\/$/);
  await expect(page.locator('main')).not.toContainText('Private ROCK');
  expect(forceLogins).toBe(1);
  await page.locator('.demo-sign-in').click();
  await page.getByLabel('Имейл',{exact:true}).fill('owner@example.invalid');
  await page.locator('.login-submit').click();
  await expect(page.locator('.profile small')).toHaveText('Администратор');
  expect(forceLogins).toBe(2);
  await page.goto('/sites/lab/devices/');
  await expect(page.getByRole('heading',{name:'ROCK',exact:true})).toBeVisible();
  await expect(page).toHaveURL(/\/sites\/lab\/devices\/$/);
  const other=await context.newPage();
  await other.goto('/sites/lab/devices/');
  await expect(other.getByRole('heading',{name:'ROCK',exact:true})).toBeVisible();
  await page.locator('.profile').click();
  await page.locator('.account-menu-logout').click();
  await expect(page).toHaveURL(/\/demo\/$/);
  await expect(page.locator('.app-shell')).toHaveAttribute('data-mode','demo');
  await expect(other).toHaveURL(/\/demo\/$/);
  await expect(page.locator('.quick-sign-in')).toBeVisible();
  await expect(other.locator('.quick-sign-in')).toBeVisible();
  await expect(other.getByRole('heading',{name:'ROCK',exact:true})).toHaveCount(0);
  await expect(other.locator('.app-shell')).toHaveAttribute('data-mode','demo');
  await other.close();
  await page.reload();
  await expect(page.locator('.quick-sign-in')).toBeVisible();
  await expect(page).toHaveURL(/\/demo\/$/);
  await expect(page.locator('.demo-mode-notice')).toBeVisible();
  expect(forceLogins).toBe(2);
});
